apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../default
images:
  - name: ghcr.io/osac-project/osac-operator
    newName: localhost/osac-operator
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: osac-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
