image:
  repository: ghcr.io/osac-project/osac-operator
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

aap:
  url: ""
  token: ""
  insecureSkipVerify: "true"
  statusPollInterval: "30s"
  templatePrefix: "osac"

fulfillment:
  serverAddress: ""
  tokenFile: ""

controllers:
  clusterOrder: true
  computeInstance: true
  tenant: true
  networking: true
  bareMetalInstance: true

configSecret:
  name: "osac-config"
  optional: true

serviceAccount:
  create: true
  name: ""
