//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/baremetal_instance_template_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A bare metal instance template defines a hardware profile (host type, OS image, network configuration)
// that can be used to create bare metal instances via a catalog item.
type BareMetalInstanceTemplate struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the template.
	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Human friendly short description of the template, suitable for displaying in one single line on a UI or CLI.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Human friendly long description of the template, using Markdown format.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Default spec values applied when creating a BareMetalInstance from this template.
	SpecDefaults  *BareMetalInstanceTemplateSpecDefaults `protobuf:"bytes,5,opt,name=spec_defaults,json=specDefaults,proto3" json:"spec_defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareMetalInstanceTemplate) Reset() {
	*x = BareMetalInstanceTemplate{}
	mi := &file_osac_private_v1_baremetal_instance_template_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareMetalInstanceTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareMetalInstanceTemplate) ProtoMessage() {}

func (x *BareMetalInstanceTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_baremetal_instance_template_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BareMetalInstanceTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BareMetalInstanceTemplate) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BareMetalInstanceTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BareMetalInstanceTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BareMetalInstanceTemplate) GetSpecDefaults() *BareMetalInstanceTemplateSpecDefaults {
	if x != nil {
		return x.SpecDefaults
	}
	return nil
}

func (x *BareMetalInstanceTemplate) SetId(v string) {
	x.Id = v
}

func (x *BareMetalInstanceTemplate) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *BareMetalInstanceTemplate) SetTitle(v string) {
	x.Title = v
}

func (x *BareMetalInstanceTemplate) SetDescription(v string) {
	x.Description = v
}

func (x *BareMetalInstanceTemplate) SetSpecDefaults(v *BareMetalInstanceTemplateSpecDefaults) {
	x.SpecDefaults = v
}

func (x *BareMetalInstanceTemplate) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *BareMetalInstanceTemplate) HasSpecDefaults() bool {
	if x == nil {
		return false
	}
	return x.SpecDefaults != nil
}

func (x *BareMetalInstanceTemplate) ClearMetadata() {
	x.Metadata = nil
}

func (x *BareMetalInstanceTemplate) ClearSpecDefaults() {
	x.SpecDefaults = nil
}

type BareMetalInstanceTemplate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the template.
	Id       string
	Metadata *Metadata
	// Human friendly short description of the template, suitable for displaying in one single line on a UI or CLI.
	Title string
	// Human friendly long description of the template, using Markdown format.
	Description string
	// Default spec values applied when creating a BareMetalInstance from this template.
	SpecDefaults *BareMetalInstanceTemplateSpecDefaults
}

func (b0 BareMetalInstanceTemplate_builder) Build() *BareMetalInstanceTemplate {
	m0 := &BareMetalInstanceTemplate{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Title = b.Title
	x.Description = b.Description
	x.SpecDefaults = b.SpecDefaults
	return m0
}

// Default values for bare metal instance spec fields.
// No overridable spec fields are defined in this initial version; fields will be added in future
// enhancements as tenant-configurable options are introduced (e.g. networking integration).
type BareMetalInstanceTemplateSpecDefaults struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareMetalInstanceTemplateSpecDefaults) Reset() {
	*x = BareMetalInstanceTemplateSpecDefaults{}
	mi := &file_osac_private_v1_baremetal_instance_template_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareMetalInstanceTemplateSpecDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareMetalInstanceTemplateSpecDefaults) ProtoMessage() {}

func (x *BareMetalInstanceTemplateSpecDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_baremetal_instance_template_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type BareMetalInstanceTemplateSpecDefaults_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 BareMetalInstanceTemplateSpecDefaults_builder) Build() *BareMetalInstanceTemplateSpecDefaults {
	m0 := &BareMetalInstanceTemplateSpecDefaults{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_baremetal_instance_template_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_baremetal_instance_template_type_proto_rawDesc = string([]byte{
	0x0a, 0x36, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x61, 0x72, 0x65, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7,
	0x01, 0x0a, 0x19, 0x42, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5b, 0x0a, 0x0d, 0x73,
	0x70, 0x65, 0x63, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x0c, 0x73, 0x70, 0x65, 0x63,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x27, 0x0a, 0x25, 0x42, 0x61, 0x72, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x73, 0x42, 0xe7, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x22, 0x42, 0x61, 0x72, 0x65, 0x6d,
	0x65, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63,
	0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var file_osac_private_v1_baremetal_instance_template_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_osac_private_v1_baremetal_instance_template_type_proto_goTypes = []any{
	(*BareMetalInstanceTemplate)(nil),             // 0: osac.private.v1.BareMetalInstanceTemplate
	(*BareMetalInstanceTemplateSpecDefaults)(nil), // 1: osac.private.v1.BareMetalInstanceTemplateSpecDefaults
	(*Metadata)(nil),                              // 2: osac.private.v1.Metadata
}
var file_osac_private_v1_baremetal_instance_template_type_proto_depIdxs = []int32{
	2, // 0: osac.private.v1.BareMetalInstanceTemplate.metadata:type_name -> osac.private.v1.Metadata
	1, // 1: osac.private.v1.BareMetalInstanceTemplate.spec_defaults:type_name -> osac.private.v1.BareMetalInstanceTemplateSpecDefaults
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_osac_private_v1_baremetal_instance_template_type_proto_init() }
func file_osac_private_v1_baremetal_instance_template_type_proto_init() {
	if File_osac_private_v1_baremetal_instance_template_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_baremetal_instance_template_type_proto_rawDesc), len(file_osac_private_v1_baremetal_instance_template_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_baremetal_instance_template_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_baremetal_instance_template_type_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_baremetal_instance_template_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_baremetal_instance_template_type_proto = out.File
	file_osac_private_v1_baremetal_instance_template_type_proto_goTypes = nil
	file_osac_private_v1_baremetal_instance_template_type_proto_depIdxs = nil
}
