//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/baremetal_instances_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BareMetalInstances_List_FullMethodName   = "/osac.private.v1.BareMetalInstances/List"
	BareMetalInstances_Get_FullMethodName    = "/osac.private.v1.BareMetalInstances/Get"
	BareMetalInstances_Create_FullMethodName = "/osac.private.v1.BareMetalInstances/Create"
	BareMetalInstances_Update_FullMethodName = "/osac.private.v1.BareMetalInstances/Update"
	BareMetalInstances_Delete_FullMethodName = "/osac.private.v1.BareMetalInstances/Delete"
	BareMetalInstances_Signal_FullMethodName = "/osac.private.v1.BareMetalInstances/Signal"
)

// BareMetalInstancesClient is the client API for BareMetalInstances service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BareMetalInstancesClient interface {
	List(ctx context.Context, in *BareMetalInstancesListRequest, opts ...grpc.CallOption) (*BareMetalInstancesListResponse, error)
	Get(ctx context.Context, in *BareMetalInstancesGetRequest, opts ...grpc.CallOption) (*BareMetalInstancesGetResponse, error)
	Create(ctx context.Context, in *BareMetalInstancesCreateRequest, opts ...grpc.CallOption) (*BareMetalInstancesCreateResponse, error)
	Update(ctx context.Context, in *BareMetalInstancesUpdateRequest, opts ...grpc.CallOption) (*BareMetalInstancesUpdateResponse, error)
	Delete(ctx context.Context, in *BareMetalInstancesDeleteRequest, opts ...grpc.CallOption) (*BareMetalInstancesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *BareMetalInstancesSignalRequest, opts ...grpc.CallOption) (*BareMetalInstancesSignalResponse, error)
}

type bareMetalInstancesClient struct {
	cc grpc.ClientConnInterface
}

func NewBareMetalInstancesClient(cc grpc.ClientConnInterface) BareMetalInstancesClient {
	return &bareMetalInstancesClient{cc}
}

func (c *bareMetalInstancesClient) List(ctx context.Context, in *BareMetalInstancesListRequest, opts ...grpc.CallOption) (*BareMetalInstancesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstancesListResponse)
	err := c.cc.Invoke(ctx, BareMetalInstances_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bareMetalInstancesClient) Get(ctx context.Context, in *BareMetalInstancesGetRequest, opts ...grpc.CallOption) (*BareMetalInstancesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstancesGetResponse)
	err := c.cc.Invoke(ctx, BareMetalInstances_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bareMetalInstancesClient) Create(ctx context.Context, in *BareMetalInstancesCreateRequest, opts ...grpc.CallOption) (*BareMetalInstancesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstancesCreateResponse)
	err := c.cc.Invoke(ctx, BareMetalInstances_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bareMetalInstancesClient) Update(ctx context.Context, in *BareMetalInstancesUpdateRequest, opts ...grpc.CallOption) (*BareMetalInstancesUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstancesUpdateResponse)
	err := c.cc.Invoke(ctx, BareMetalInstances_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bareMetalInstancesClient) Delete(ctx context.Context, in *BareMetalInstancesDeleteRequest, opts ...grpc.CallOption) (*BareMetalInstancesDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstancesDeleteResponse)
	err := c.cc.Invoke(ctx, BareMetalInstances_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bareMetalInstancesClient) Signal(ctx context.Context, in *BareMetalInstancesSignalRequest, opts ...grpc.CallOption) (*BareMetalInstancesSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstancesSignalResponse)
	err := c.cc.Invoke(ctx, BareMetalInstances_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BareMetalInstancesServer is the server API for BareMetalInstances service.
// All implementations must embed UnimplementedBareMetalInstancesServer
// for forward compatibility.
type BareMetalInstancesServer interface {
	List(context.Context, *BareMetalInstancesListRequest) (*BareMetalInstancesListResponse, error)
	Get(context.Context, *BareMetalInstancesGetRequest) (*BareMetalInstancesGetResponse, error)
	Create(context.Context, *BareMetalInstancesCreateRequest) (*BareMetalInstancesCreateResponse, error)
	Update(context.Context, *BareMetalInstancesUpdateRequest) (*BareMetalInstancesUpdateResponse, error)
	Delete(context.Context, *BareMetalInstancesDeleteRequest) (*BareMetalInstancesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *BareMetalInstancesSignalRequest) (*BareMetalInstancesSignalResponse, error)
	mustEmbedUnimplementedBareMetalInstancesServer()
}

// UnimplementedBareMetalInstancesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBareMetalInstancesServer struct{}

func (UnimplementedBareMetalInstancesServer) List(context.Context, *BareMetalInstancesListRequest) (*BareMetalInstancesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBareMetalInstancesServer) Get(context.Context, *BareMetalInstancesGetRequest) (*BareMetalInstancesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBareMetalInstancesServer) Create(context.Context, *BareMetalInstancesCreateRequest) (*BareMetalInstancesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBareMetalInstancesServer) Update(context.Context, *BareMetalInstancesUpdateRequest) (*BareMetalInstancesUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBareMetalInstancesServer) Delete(context.Context, *BareMetalInstancesDeleteRequest) (*BareMetalInstancesDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBareMetalInstancesServer) Signal(context.Context, *BareMetalInstancesSignalRequest) (*BareMetalInstancesSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedBareMetalInstancesServer) mustEmbedUnimplementedBareMetalInstancesServer() {}
func (UnimplementedBareMetalInstancesServer) testEmbeddedByValue()                            {}

// UnsafeBareMetalInstancesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BareMetalInstancesServer will
// result in compilation errors.
type UnsafeBareMetalInstancesServer interface {
	mustEmbedUnimplementedBareMetalInstancesServer()
}

func RegisterBareMetalInstancesServer(s grpc.ServiceRegistrar, srv BareMetalInstancesServer) {
	// If the following call pancis, it indicates UnimplementedBareMetalInstancesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BareMetalInstances_ServiceDesc, srv)
}

func _BareMetalInstances_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstancesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstancesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstances_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstancesServer).List(ctx, req.(*BareMetalInstancesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BareMetalInstances_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstancesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstancesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstances_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstancesServer).Get(ctx, req.(*BareMetalInstancesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BareMetalInstances_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstancesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstancesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstances_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstancesServer).Create(ctx, req.(*BareMetalInstancesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BareMetalInstances_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstancesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstancesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstances_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstancesServer).Update(ctx, req.(*BareMetalInstancesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BareMetalInstances_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstancesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstancesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstances_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstancesServer).Delete(ctx, req.(*BareMetalInstancesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BareMetalInstances_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstancesSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstancesServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstances_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstancesServer).Signal(ctx, req.(*BareMetalInstancesSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BareMetalInstances_ServiceDesc is the grpc.ServiceDesc for BareMetalInstances service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BareMetalInstances_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.BareMetalInstances",
	HandlerType: (*BareMetalInstancesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BareMetalInstances_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BareMetalInstances_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BareMetalInstances_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BareMetalInstances_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BareMetalInstances_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _BareMetalInstances_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/baremetal_instances_service.proto",
}
