//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/instance_types_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstanceTypes_List_FullMethodName   = "/osac.private.v1.InstanceTypes/List"
	InstanceTypes_Get_FullMethodName    = "/osac.private.v1.InstanceTypes/Get"
	InstanceTypes_Create_FullMethodName = "/osac.private.v1.InstanceTypes/Create"
	InstanceTypes_Update_FullMethodName = "/osac.private.v1.InstanceTypes/Update"
	InstanceTypes_Delete_FullMethodName = "/osac.private.v1.InstanceTypes/Delete"
	InstanceTypes_Signal_FullMethodName = "/osac.private.v1.InstanceTypes/Signal"
)

// InstanceTypesClient is the client API for InstanceTypes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstanceTypesClient interface {
	List(ctx context.Context, in *InstanceTypesListRequest, opts ...grpc.CallOption) (*InstanceTypesListResponse, error)
	Get(ctx context.Context, in *InstanceTypesGetRequest, opts ...grpc.CallOption) (*InstanceTypesGetResponse, error)
	Create(ctx context.Context, in *InstanceTypesCreateRequest, opts ...grpc.CallOption) (*InstanceTypesCreateResponse, error)
	Update(ctx context.Context, in *InstanceTypesUpdateRequest, opts ...grpc.CallOption) (*InstanceTypesUpdateResponse, error)
	Delete(ctx context.Context, in *InstanceTypesDeleteRequest, opts ...grpc.CallOption) (*InstanceTypesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *InstanceTypesSignalRequest, opts ...grpc.CallOption) (*InstanceTypesSignalResponse, error)
}

type instanceTypesClient struct {
	cc grpc.ClientConnInterface
}

func NewInstanceTypesClient(cc grpc.ClientConnInterface) InstanceTypesClient {
	return &instanceTypesClient{cc}
}

func (c *instanceTypesClient) List(ctx context.Context, in *InstanceTypesListRequest, opts ...grpc.CallOption) (*InstanceTypesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceTypesListResponse)
	err := c.cc.Invoke(ctx, InstanceTypes_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceTypesClient) Get(ctx context.Context, in *InstanceTypesGetRequest, opts ...grpc.CallOption) (*InstanceTypesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceTypesGetResponse)
	err := c.cc.Invoke(ctx, InstanceTypes_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceTypesClient) Create(ctx context.Context, in *InstanceTypesCreateRequest, opts ...grpc.CallOption) (*InstanceTypesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceTypesCreateResponse)
	err := c.cc.Invoke(ctx, InstanceTypes_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceTypesClient) Update(ctx context.Context, in *InstanceTypesUpdateRequest, opts ...grpc.CallOption) (*InstanceTypesUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceTypesUpdateResponse)
	err := c.cc.Invoke(ctx, InstanceTypes_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceTypesClient) Delete(ctx context.Context, in *InstanceTypesDeleteRequest, opts ...grpc.CallOption) (*InstanceTypesDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceTypesDeleteResponse)
	err := c.cc.Invoke(ctx, InstanceTypes_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceTypesClient) Signal(ctx context.Context, in *InstanceTypesSignalRequest, opts ...grpc.CallOption) (*InstanceTypesSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceTypesSignalResponse)
	err := c.cc.Invoke(ctx, InstanceTypes_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstanceTypesServer is the server API for InstanceTypes service.
// All implementations must embed UnimplementedInstanceTypesServer
// for forward compatibility.
type InstanceTypesServer interface {
	List(context.Context, *InstanceTypesListRequest) (*InstanceTypesListResponse, error)
	Get(context.Context, *InstanceTypesGetRequest) (*InstanceTypesGetResponse, error)
	Create(context.Context, *InstanceTypesCreateRequest) (*InstanceTypesCreateResponse, error)
	Update(context.Context, *InstanceTypesUpdateRequest) (*InstanceTypesUpdateResponse, error)
	Delete(context.Context, *InstanceTypesDeleteRequest) (*InstanceTypesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *InstanceTypesSignalRequest) (*InstanceTypesSignalResponse, error)
	mustEmbedUnimplementedInstanceTypesServer()
}

// UnimplementedInstanceTypesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstanceTypesServer struct{}

func (UnimplementedInstanceTypesServer) List(context.Context, *InstanceTypesListRequest) (*InstanceTypesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedInstanceTypesServer) Get(context.Context, *InstanceTypesGetRequest) (*InstanceTypesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedInstanceTypesServer) Create(context.Context, *InstanceTypesCreateRequest) (*InstanceTypesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedInstanceTypesServer) Update(context.Context, *InstanceTypesUpdateRequest) (*InstanceTypesUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedInstanceTypesServer) Delete(context.Context, *InstanceTypesDeleteRequest) (*InstanceTypesDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedInstanceTypesServer) Signal(context.Context, *InstanceTypesSignalRequest) (*InstanceTypesSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedInstanceTypesServer) mustEmbedUnimplementedInstanceTypesServer() {}
func (UnimplementedInstanceTypesServer) testEmbeddedByValue()                       {}

// UnsafeInstanceTypesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstanceTypesServer will
// result in compilation errors.
type UnsafeInstanceTypesServer interface {
	mustEmbedUnimplementedInstanceTypesServer()
}

func RegisterInstanceTypesServer(s grpc.ServiceRegistrar, srv InstanceTypesServer) {
	// If the following call pancis, it indicates UnimplementedInstanceTypesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstanceTypes_ServiceDesc, srv)
}

func _InstanceTypes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTypesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceTypesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceTypes_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceTypesServer).List(ctx, req.(*InstanceTypesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceTypes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTypesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceTypesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceTypes_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceTypesServer).Get(ctx, req.(*InstanceTypesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceTypes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTypesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceTypesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceTypes_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceTypesServer).Create(ctx, req.(*InstanceTypesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceTypes_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTypesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceTypesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceTypes_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceTypesServer).Update(ctx, req.(*InstanceTypesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceTypes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTypesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceTypesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceTypes_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceTypesServer).Delete(ctx, req.(*InstanceTypesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceTypes_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTypesSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceTypesServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceTypes_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceTypesServer).Signal(ctx, req.(*InstanceTypesSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstanceTypes_ServiceDesc is the grpc.ServiceDesc for InstanceTypes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstanceTypes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.InstanceTypes",
	HandlerType: (*InstanceTypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _InstanceTypes_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _InstanceTypes_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _InstanceTypes_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _InstanceTypes_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _InstanceTypes_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _InstanceTypes_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/instance_types_service.proto",
}
