//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/instance_type_type.proto

//go:build protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for InstanceType resources.
type InstanceTypeState int32

const (
	// State is unknown or has not been determined yet.
	InstanceTypeState_INSTANCE_TYPE_STATE_UNSPECIFIED InstanceTypeState = 0
	// The instance type is fully available for new VM creation.
	InstanceTypeState_INSTANCE_TYPE_STATE_ACTIVE InstanceTypeState = 1
	// The instance type is available with warnings; migration to a replacement is recommended.
	InstanceTypeState_INSTANCE_TYPE_STATE_DEPRECATED InstanceTypeState = 2
	// The instance type is not available for new VMs; visible for lookups only.
	InstanceTypeState_INSTANCE_TYPE_STATE_OBSOLETE InstanceTypeState = 3
)

// Enum value maps for InstanceTypeState.
var (
	InstanceTypeState_name = map[int32]string{
		0: "INSTANCE_TYPE_STATE_UNSPECIFIED",
		1: "INSTANCE_TYPE_STATE_ACTIVE",
		2: "INSTANCE_TYPE_STATE_DEPRECATED",
		3: "INSTANCE_TYPE_STATE_OBSOLETE",
	}
	InstanceTypeState_value = map[string]int32{
		"INSTANCE_TYPE_STATE_UNSPECIFIED": 0,
		"INSTANCE_TYPE_STATE_ACTIVE":      1,
		"INSTANCE_TYPE_STATE_DEPRECATED":  2,
		"INSTANCE_TYPE_STATE_OBSOLETE":    3,
	}
)

func (x InstanceTypeState) Enum() *InstanceTypeState {
	p := new(InstanceTypeState)
	*p = x
	return p
}

func (x InstanceTypeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceTypeState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_instance_type_type_proto_enumTypes[0].Descriptor()
}

func (InstanceTypeState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_instance_type_type_proto_enumTypes[0]
}

func (x InstanceTypeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Contains deprecation details for an instance type.
//
// This message is only meaningful when the parent InstanceType state is DEPRECATED or OBSOLETE.
// The state field mirrors the parent InstanceType spec state, making this message self-contained
// when serialized independently.
type InstanceTypeDeprecation struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State                 InstanceTypeState      `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.InstanceTypeState"`
	xxx_hidden_Replacement           string                 `protobuf:"bytes,2,opt,name=replacement,proto3"`
	xxx_hidden_DeprecationTimestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deprecation_timestamp,json=deprecationTimestamp,proto3"`
	xxx_hidden_ObsolescenceTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=obsolescence_timestamp,json=obsolescenceTimestamp,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *InstanceTypeDeprecation) Reset() {
	*x = InstanceTypeDeprecation{}
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceTypeDeprecation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceTypeDeprecation) ProtoMessage() {}

func (x *InstanceTypeDeprecation) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceTypeDeprecation) GetState() InstanceTypeState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return InstanceTypeState_INSTANCE_TYPE_STATE_UNSPECIFIED
}

func (x *InstanceTypeDeprecation) GetReplacement() string {
	if x != nil {
		return x.xxx_hidden_Replacement
	}
	return ""
}

func (x *InstanceTypeDeprecation) GetDeprecationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeprecationTimestamp
	}
	return nil
}

func (x *InstanceTypeDeprecation) GetObsolescenceTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ObsolescenceTimestamp
	}
	return nil
}

func (x *InstanceTypeDeprecation) SetState(v InstanceTypeState) {
	x.xxx_hidden_State = v
}

func (x *InstanceTypeDeprecation) SetReplacement(v string) {
	x.xxx_hidden_Replacement = v
}

func (x *InstanceTypeDeprecation) SetDeprecationTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeprecationTimestamp = v
}

func (x *InstanceTypeDeprecation) SetObsolescenceTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_ObsolescenceTimestamp = v
}

func (x *InstanceTypeDeprecation) HasDeprecationTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeprecationTimestamp != nil
}

func (x *InstanceTypeDeprecation) HasObsolescenceTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ObsolescenceTimestamp != nil
}

func (x *InstanceTypeDeprecation) ClearDeprecationTimestamp() {
	x.xxx_hidden_DeprecationTimestamp = nil
}

func (x *InstanceTypeDeprecation) ClearObsolescenceTimestamp() {
	x.xxx_hidden_ObsolescenceTimestamp = nil
}

type InstanceTypeDeprecation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current deprecation state (DEPRECATED or OBSOLETE). Mirrors the spec-level state.
	State InstanceTypeState
	// Suggested replacement instance type name (e.g., "standard-8-32").
	Replacement string
	// When deprecation was announced. Auto-set on transition to DEPRECATED.
	DeprecationTimestamp *timestamppb.Timestamp
	// When the instance type becomes or became obsolete. Admin-specified or auto-set on transition to OBSOLETE.
	ObsolescenceTimestamp *timestamppb.Timestamp
}

func (b0 InstanceTypeDeprecation_builder) Build() *InstanceTypeDeprecation {
	m0 := &InstanceTypeDeprecation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Replacement = b.Replacement
	x.xxx_hidden_DeprecationTimestamp = b.DeprecationTimestamp
	x.xxx_hidden_ObsolescenceTimestamp = b.ObsolescenceTimestamp
	return m0
}

// Contains the details about the instance type that are available only for the system.
//
// Instance types are admin-managed catalog resources that define pre-configured compute bundles
// (cores, memory) referenced by name when creating VMs. Cloud Provider Admins control the available
// configurations through lifecycle-managed instance types.
//
// The `spec` contains the desired configuration, and may be modified by the admin. The `status` contains the
// current state of the instance type, is provided by the system and can't be modified by the user.
type InstanceType struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *InstanceTypeSpec      `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *InstanceTypeStatus    `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstanceType) Reset() {
	*x = InstanceType{}
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceType) ProtoMessage() {}

func (x *InstanceType) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceType) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *InstanceType) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *InstanceType) GetSpec() *InstanceTypeSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *InstanceType) GetStatus() *InstanceTypeStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *InstanceType) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *InstanceType) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *InstanceType) SetSpec(v *InstanceTypeSpec) {
	x.xxx_hidden_Spec = v
}

func (x *InstanceType) SetStatus(v *InstanceTypeStatus) {
	x.xxx_hidden_Status = v
}

func (x *InstanceType) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *InstanceType) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *InstanceType) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *InstanceType) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *InstanceType) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *InstanceType) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type InstanceType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the instance type.
	Id string
	// Metadata of the instance type, including name, labels, tenant, and timestamps.
	Metadata *Metadata
	// Desired configuration of the instance type (admin-modifiable).
	Spec *InstanceTypeSpec
	// Current state of the instance type (system-provided, read-only).
	Status *InstanceTypeStatus
}

func (b0 InstanceType_builder) Build() *InstanceType {
	m0 := &InstanceType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// Defines the desired configuration for an InstanceType.
//
// The spec contains admin-specified parameters that define the compute bundle. The `cores` and `memory_gib`
// fields are immutable after creation. The `description`, `state`, and `deprecation` fields may be updated
// to manage the instance type lifecycle.
type InstanceTypeSpec struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Cores       int32                    `protobuf:"varint,1,opt,name=cores,proto3"`
	xxx_hidden_MemoryGib   int32                    `protobuf:"varint,2,opt,name=memory_gib,json=memoryGib,proto3"`
	xxx_hidden_Description string                   `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_State       InstanceTypeState        `protobuf:"varint,4,opt,name=state,proto3,enum=osac.private.v1.InstanceTypeState"`
	xxx_hidden_Deprecation *InstanceTypeDeprecation `protobuf:"bytes,5,opt,name=deprecation,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InstanceTypeSpec) Reset() {
	*x = InstanceTypeSpec{}
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceTypeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceTypeSpec) ProtoMessage() {}

func (x *InstanceTypeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceTypeSpec) GetCores() int32 {
	if x != nil {
		return x.xxx_hidden_Cores
	}
	return 0
}

func (x *InstanceTypeSpec) GetMemoryGib() int32 {
	if x != nil {
		return x.xxx_hidden_MemoryGib
	}
	return 0
}

func (x *InstanceTypeSpec) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *InstanceTypeSpec) GetState() InstanceTypeState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return InstanceTypeState_INSTANCE_TYPE_STATE_UNSPECIFIED
}

func (x *InstanceTypeSpec) GetDeprecation() *InstanceTypeDeprecation {
	if x != nil {
		return x.xxx_hidden_Deprecation
	}
	return nil
}

func (x *InstanceTypeSpec) SetCores(v int32) {
	x.xxx_hidden_Cores = v
}

func (x *InstanceTypeSpec) SetMemoryGib(v int32) {
	x.xxx_hidden_MemoryGib = v
}

func (x *InstanceTypeSpec) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *InstanceTypeSpec) SetState(v InstanceTypeState) {
	x.xxx_hidden_State = v
}

func (x *InstanceTypeSpec) SetDeprecation(v *InstanceTypeDeprecation) {
	x.xxx_hidden_Deprecation = v
}

func (x *InstanceTypeSpec) HasDeprecation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Deprecation != nil
}

func (x *InstanceTypeSpec) ClearDeprecation() {
	x.xxx_hidden_Deprecation = nil
}

type InstanceTypeSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of CPU cores. Immutable after creation.
	Cores int32
	// Amount of memory in GiB. Immutable after creation.
	MemoryGib int32
	// Human friendly description of the instance type, using Markdown format.
	Description string
	// Current lifecycle state of the instance type.
	State InstanceTypeState
	// Deprecation details. Only meaningful when state is DEPRECATED or OBSOLETE.
	Deprecation *InstanceTypeDeprecation
}

func (b0 InstanceTypeSpec_builder) Build() *InstanceTypeSpec {
	m0 := &InstanceTypeSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cores = b.Cores
	x.xxx_hidden_MemoryGib = b.MemoryGib
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Deprecation = b.Deprecation
	return m0
}

// Contains the system-provided status of an InstanceType.
//
// Currently empty. Reserved for future reconciliation state.
type InstanceTypeStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceTypeStatus) Reset() {
	*x = InstanceTypeStatus{}
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceTypeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceTypeStatus) ProtoMessage() {}

func (x *InstanceTypeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_instance_type_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InstanceTypeStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InstanceTypeStatus_builder) Build() *InstanceTypeStatus {
	m0 := &InstanceTypeStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_instance_type_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_instance_type_type_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73,
	0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x99, 0x02, 0x0a, 0x17, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4f, 0x0a, 0x15, 0x64, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x51, 0x0a, 0x16, 0x6f, 0x62,
	0x73, 0x6f, 0x6c, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x15, 0x6f, 0x62, 0x73, 0x6f, 0x6c, 0x65, 0x73, 0x63,
	0x65, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xc9, 0x01,
	0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x10, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67,
	0x69, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x47, 0x69, 0x62, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x4a, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2a, 0x9e, 0x01, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4e, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a,
	0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e,
	0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x50, 0x52, 0x45, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x20, 0x0a, 0x1c, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x42, 0x53, 0x4f, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x03, 0x42, 0xda, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f,
	0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73,
	0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_instance_type_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_instance_type_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_instance_type_type_proto_goTypes = []any{
	(InstanceTypeState)(0),          // 0: osac.private.v1.InstanceTypeState
	(*InstanceTypeDeprecation)(nil), // 1: osac.private.v1.InstanceTypeDeprecation
	(*InstanceType)(nil),            // 2: osac.private.v1.InstanceType
	(*InstanceTypeSpec)(nil),        // 3: osac.private.v1.InstanceTypeSpec
	(*InstanceTypeStatus)(nil),      // 4: osac.private.v1.InstanceTypeStatus
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*Metadata)(nil),                // 6: osac.private.v1.Metadata
}
var file_osac_private_v1_instance_type_type_proto_depIdxs = []int32{
	0, // 0: osac.private.v1.InstanceTypeDeprecation.state:type_name -> osac.private.v1.InstanceTypeState
	5, // 1: osac.private.v1.InstanceTypeDeprecation.deprecation_timestamp:type_name -> google.protobuf.Timestamp
	5, // 2: osac.private.v1.InstanceTypeDeprecation.obsolescence_timestamp:type_name -> google.protobuf.Timestamp
	6, // 3: osac.private.v1.InstanceType.metadata:type_name -> osac.private.v1.Metadata
	3, // 4: osac.private.v1.InstanceType.spec:type_name -> osac.private.v1.InstanceTypeSpec
	4, // 5: osac.private.v1.InstanceType.status:type_name -> osac.private.v1.InstanceTypeStatus
	0, // 6: osac.private.v1.InstanceTypeSpec.state:type_name -> osac.private.v1.InstanceTypeState
	1, // 7: osac.private.v1.InstanceTypeSpec.deprecation:type_name -> osac.private.v1.InstanceTypeDeprecation
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_osac_private_v1_instance_type_type_proto_init() }
func file_osac_private_v1_instance_type_type_proto_init() {
	if File_osac_private_v1_instance_type_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_instance_type_type_proto_rawDesc), len(file_osac_private_v1_instance_type_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_instance_type_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_instance_type_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_instance_type_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_instance_type_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_instance_type_type_proto = out.File
	file_osac_private_v1_instance_type_type_proto_goTypes = nil
	file_osac_private_v1_instance_type_type_proto_depIdxs = nil
}
