//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/network_class_type.proto

//go:build protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for NetworkClass resources.
type NetworkClassState int32

const (
	// State is unknown or has not been determined yet.
	NetworkClassState_NETWORK_CLASS_STATE_UNSPECIFIED NetworkClassState = 0
	// The network class is being initialized and is not yet ready for use.
	NetworkClassState_NETWORK_CLASS_STATE_PENDING NetworkClassState = 1
	// The network class is fully operational and available for creating VirtualNetworks.
	NetworkClassState_NETWORK_CLASS_STATE_READY NetworkClassState = 2
	// The network class has encountered an error and cannot be used for creating VirtualNetworks.
	NetworkClassState_NETWORK_CLASS_STATE_FAILED NetworkClassState = 3
)

// Enum value maps for NetworkClassState.
var (
	NetworkClassState_name = map[int32]string{
		0: "NETWORK_CLASS_STATE_UNSPECIFIED",
		1: "NETWORK_CLASS_STATE_PENDING",
		2: "NETWORK_CLASS_STATE_READY",
		3: "NETWORK_CLASS_STATE_FAILED",
	}
	NetworkClassState_value = map[string]int32{
		"NETWORK_CLASS_STATE_UNSPECIFIED": 0,
		"NETWORK_CLASS_STATE_PENDING":     1,
		"NETWORK_CLASS_STATE_READY":       2,
		"NETWORK_CLASS_STATE_FAILED":      3,
	}
)

func (x NetworkClassState) Enum() *NetworkClassState {
	p := new(NetworkClassState)
	*p = x
	return p
}

func (x NetworkClassState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkClassState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_network_class_type_proto_enumTypes[0].Descriptor()
}

func (NetworkClassState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_network_class_type_proto_enumTypes[0]
}

func (x NetworkClassState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Describes a network implementation strategy available for creating virtual networks.
//
// NetworkClass represents a specific network backend implementation that VirtualNetworks can use. For example,
// there could be a network class `udn-net` to describe networks implemented using User-Defined Networks in
// Kubernetes, and another `phys-net` for networks backed by physical network infrastructure.
//
// This is similar to the _storage class_ concept used by Kubernetes for persistent volumes, or the _instance type_
// concept used by cloud providers for compute resources.
//
// Users query available NetworkClasses to discover which network implementation strategies they can choose when
// creating VirtualNetworks. The `implementation_strategy` field is the key identifier that VirtualNetwork resources
// reference to select their network backend.
type NetworkClass struct {
	state                             protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Id                     string                    `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata               *Metadata                 `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Title                  string                    `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Description            string                    `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_ImplementationStrategy string                    `protobuf:"bytes,5,opt,name=implementation_strategy,json=implementationStrategy,proto3"`
	xxx_hidden_Constraints            *NetworkClassConstraints  `protobuf:"bytes,6,opt,name=constraints,proto3"`
	xxx_hidden_Capabilities           *NetworkClassCapabilities `protobuf:"bytes,7,opt,name=capabilities,proto3"`
	xxx_hidden_Status                 *NetworkClassStatus       `protobuf:"bytes,8,opt,name=status,proto3"`
	xxx_hidden_IsDefault              bool                      `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3,oneof"`
	xxx_hidden_FabricManager          string                    `protobuf:"bytes,10,opt,name=fabric_manager,json=fabricManager,proto3"`
	xxx_hidden_K8SManager             *string                   `protobuf:"bytes,11,opt,name=k8s_manager,json=k8sManager,proto3,oneof"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *NetworkClass) Reset() {
	*x = NetworkClass{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClass) ProtoMessage() {}

func (x *NetworkClass) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClass) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *NetworkClass) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *NetworkClass) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *NetworkClass) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *NetworkClass) GetImplementationStrategy() string {
	if x != nil {
		return x.xxx_hidden_ImplementationStrategy
	}
	return ""
}

func (x *NetworkClass) GetConstraints() *NetworkClassConstraints {
	if x != nil {
		return x.xxx_hidden_Constraints
	}
	return nil
}

func (x *NetworkClass) GetCapabilities() *NetworkClassCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *NetworkClass) GetStatus() *NetworkClassStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *NetworkClass) GetIsDefault() bool {
	if x != nil {
		return x.xxx_hidden_IsDefault
	}
	return false
}

func (x *NetworkClass) GetFabricManager() string {
	if x != nil {
		return x.xxx_hidden_FabricManager
	}
	return ""
}

func (x *NetworkClass) GetK8SManager() string {
	if x != nil {
		if x.xxx_hidden_K8SManager != nil {
			return *x.xxx_hidden_K8SManager
		}
		return ""
	}
	return ""
}

func (x *NetworkClass) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *NetworkClass) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *NetworkClass) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *NetworkClass) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *NetworkClass) SetImplementationStrategy(v string) {
	x.xxx_hidden_ImplementationStrategy = v
}

func (x *NetworkClass) SetConstraints(v *NetworkClassConstraints) {
	x.xxx_hidden_Constraints = v
}

func (x *NetworkClass) SetCapabilities(v *NetworkClassCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *NetworkClass) SetStatus(v *NetworkClassStatus) {
	x.xxx_hidden_Status = v
}

func (x *NetworkClass) SetIsDefault(v bool) {
	x.xxx_hidden_IsDefault = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *NetworkClass) SetFabricManager(v string) {
	x.xxx_hidden_FabricManager = v
}

func (x *NetworkClass) SetK8SManager(v string) {
	x.xxx_hidden_K8SManager = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *NetworkClass) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *NetworkClass) HasConstraints() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Constraints != nil
}

func (x *NetworkClass) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *NetworkClass) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *NetworkClass) HasIsDefault() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *NetworkClass) HasK8SManager() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *NetworkClass) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *NetworkClass) ClearConstraints() {
	x.xxx_hidden_Constraints = nil
}

func (x *NetworkClass) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

func (x *NetworkClass) ClearStatus() {
	x.xxx_hidden_Status = nil
}

func (x *NetworkClass) ClearIsDefault() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_IsDefault = false
}

func (x *NetworkClass) ClearK8SManager() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_K8SManager = nil
}

type NetworkClass_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the network class.
	Id string
	// Metadata of the network class.
	Metadata *Metadata
	// Human friendly short description of the network class, only a few words, suitable for displaying in one single
	// line on a UI or CLI. For example: "UDN Network" or "Physical Network".
	Title string
	// Human friendly long description of the network class, using Markdown format. This should explain the
	// characteristics of networks created using this class, including performance characteristics, isolation
	// guarantees, and any limitations or requirements.
	Description string
	// Implementation strategy identifier for this network class. This is the discriminator that VirtualNetwork
	// resources use to select which network backend to use. For example: "udn-net", "phys-net", "ovn-kubernetes".
	//
	// This value is system-defined and immutable once the NetworkClass is created.
	ImplementationStrategy string
	// Class-specific configuration constraints and options. These define implementation-specific parameters that
	// networks using this class must or may configure.
	Constraints *NetworkClassConstraints
	// Capabilities that this network class supports. These describe what features are available when using this
	// network implementation strategy.
	Capabilities *NetworkClassCapabilities
	// Current operational status of the network class.
	Status *NetworkClassStatus
	// Whether this NetworkClass is the default. Only one NetworkClass can be the default at a time.
	// When a VirtualNetwork is created without specifying network_class, the default NetworkClass is used.
	IsDefault *bool
	// Identifier of the fabric manager that handles physical network operations for this class. The fabric manager
	// controls all fabric-level operations: virtual network segments, security groups, external IPs, and NAT gateways.
	// For example: "netris", "neutron".
	FabricManager string
	// Identifier of the K8s manager that bridges the Kubernetes overlay to the physical fabric. Only needed for regions
	// that host VMs — the K8s manager creates the overlay network on hosting clusters and bridges it to the fabric
	// segment. For example: "cudn_localnet". If not set, the region does not support VM workloads.
	K8SManager *string
}

func (b0 NetworkClass_builder) Build() *NetworkClass {
	m0 := &NetworkClass{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_ImplementationStrategy = b.ImplementationStrategy
	x.xxx_hidden_Constraints = b.Constraints
	x.xxx_hidden_Capabilities = b.Capabilities
	x.xxx_hidden_Status = b.Status
	if b.IsDefault != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_IsDefault = *b.IsDefault
	}
	x.xxx_hidden_FabricManager = b.FabricManager
	if b.K8SManager != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_K8SManager = b.K8SManager
	}
	return m0
}

// Defines configuration constraints for a specific NetworkClass implementation.
//
// This message contains implementation-specific parameters that may be required or optional when creating
// VirtualNetworks using this class. Currently minimal to allow for future extension.
type NetworkClassConstraints struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClassConstraints) Reset() {
	*x = NetworkClassConstraints{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassConstraints) ProtoMessage() {}

func (x *NetworkClassConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type NetworkClassConstraints_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 NetworkClassConstraints_builder) Build() *NetworkClassConstraints {
	m0 := &NetworkClassConstraints{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Describes the capabilities supported by a NetworkClass.
//
// These fields indicate what network features are available when using this class for VirtualNetwork creation.
type NetworkClassCapabilities struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SupportsIpv4      bool                   `protobuf:"varint,1,opt,name=supports_ipv4,json=supportsIpv4,proto3"`
	xxx_hidden_SupportsIpv6      bool                   `protobuf:"varint,2,opt,name=supports_ipv6,json=supportsIpv6,proto3"`
	xxx_hidden_SupportsDualStack bool                   `protobuf:"varint,3,opt,name=supports_dual_stack,json=supportsDualStack,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *NetworkClassCapabilities) Reset() {
	*x = NetworkClassCapabilities{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassCapabilities) ProtoMessage() {}

func (x *NetworkClassCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClassCapabilities) GetSupportsIpv4() bool {
	if x != nil {
		return x.xxx_hidden_SupportsIpv4
	}
	return false
}

func (x *NetworkClassCapabilities) GetSupportsIpv6() bool {
	if x != nil {
		return x.xxx_hidden_SupportsIpv6
	}
	return false
}

func (x *NetworkClassCapabilities) GetSupportsDualStack() bool {
	if x != nil {
		return x.xxx_hidden_SupportsDualStack
	}
	return false
}

func (x *NetworkClassCapabilities) SetSupportsIpv4(v bool) {
	x.xxx_hidden_SupportsIpv4 = v
}

func (x *NetworkClassCapabilities) SetSupportsIpv6(v bool) {
	x.xxx_hidden_SupportsIpv6 = v
}

func (x *NetworkClassCapabilities) SetSupportsDualStack(v bool) {
	x.xxx_hidden_SupportsDualStack = v
}

type NetworkClassCapabilities_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether this network class supports IPv4 addressing.
	SupportsIpv4 bool
	// Whether this network class supports IPv6 addressing.
	SupportsIpv6 bool
	// Whether this network class supports dual-stack (IPv4 + IPv6) configuration.
	SupportsDualStack bool
}

func (b0 NetworkClassCapabilities_builder) Build() *NetworkClassCapabilities {
	m0 := &NetworkClassCapabilities{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SupportsIpv4 = b.SupportsIpv4
	x.xxx_hidden_SupportsIpv6 = b.SupportsIpv6
	x.xxx_hidden_SupportsDualStack = b.SupportsDualStack
	return m0
}

// Represents the current operational state of a NetworkClass.
type NetworkClassStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       NetworkClassState      `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.NetworkClassState"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	xxx_hidden_Hub         string                 `protobuf:"bytes,3,opt,name=hub,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NetworkClassStatus) Reset() {
	*x = NetworkClassStatus{}
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassStatus) ProtoMessage() {}

func (x *NetworkClassStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_network_class_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClassStatus) GetState() NetworkClassState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return NetworkClassState_NETWORK_CLASS_STATE_UNSPECIFIED
}

func (x *NetworkClassStatus) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *NetworkClassStatus) GetHub() string {
	if x != nil {
		return x.xxx_hidden_Hub
	}
	return ""
}

func (x *NetworkClassStatus) SetState(v NetworkClassState) {
	x.xxx_hidden_State = v
}

func (x *NetworkClassStatus) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *NetworkClassStatus) SetHub(v string) {
	x.xxx_hidden_Hub = v
}

func (x *NetworkClassStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NetworkClassStatus) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type NetworkClassStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the network class.
	State NetworkClassState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this message might explain what went wrong.
	Message *string
	// Identifier of the hub that was selected for this network class.
	// This is system-managed and used by the controller to track which hub cluster manages this class's resources.
	Hub string
}

func (b0 NetworkClassStatus_builder) Build() *NetworkClassStatus {
	m0 := &NetworkClassStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_Hub = b.Hub
	return m0
}

var File_osac_private_v1_network_class_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_network_class_type_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xae, 0x04, 0x0a, 0x0c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x37, 0x0a, 0x17, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x16, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x4a, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x4d, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x22, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0b,
	0x6b, 0x38, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0a, 0x6b, 0x38, 0x73, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6b, 0x38, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x22, 0x19, 0x0a, 0x17, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x94, 0x01, 0x0a,
	0x18, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x49, 0x70, 0x76, 0x34, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x49,
	0x70, 0x76, 0x36, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f,
	0x64, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x44, 0x75, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x63, 0x6b, 0x22, 0x8b, 0x01, 0x0a, 0x12, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x68, 0x75, 0x62, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2a, 0x98, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x4e, 0x45, 0x54, 0x57, 0x4f,
	0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b,
	0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1d, 0x0a,
	0x19, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a,
	0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xda, 0x01, 0x0a,
	0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50,
	0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var file_osac_private_v1_network_class_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_network_class_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_network_class_type_proto_goTypes = []any{
	(NetworkClassState)(0),           // 0: osac.private.v1.NetworkClassState
	(*NetworkClass)(nil),             // 1: osac.private.v1.NetworkClass
	(*NetworkClassConstraints)(nil),  // 2: osac.private.v1.NetworkClassConstraints
	(*NetworkClassCapabilities)(nil), // 3: osac.private.v1.NetworkClassCapabilities
	(*NetworkClassStatus)(nil),       // 4: osac.private.v1.NetworkClassStatus
	(*Metadata)(nil),                 // 5: osac.private.v1.Metadata
}
var file_osac_private_v1_network_class_type_proto_depIdxs = []int32{
	5, // 0: osac.private.v1.NetworkClass.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.NetworkClass.constraints:type_name -> osac.private.v1.NetworkClassConstraints
	3, // 2: osac.private.v1.NetworkClass.capabilities:type_name -> osac.private.v1.NetworkClassCapabilities
	4, // 3: osac.private.v1.NetworkClass.status:type_name -> osac.private.v1.NetworkClassStatus
	0, // 4: osac.private.v1.NetworkClassStatus.state:type_name -> osac.private.v1.NetworkClassState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_network_class_type_proto_init() }
func file_osac_private_v1_network_class_type_proto_init() {
	if File_osac_private_v1_network_class_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_network_class_type_proto_msgTypes[0].OneofWrappers = []any{}
	file_osac_private_v1_network_class_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_network_class_type_proto_rawDesc), len(file_osac_private_v1_network_class_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_network_class_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_network_class_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_network_class_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_network_class_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_network_class_type_proto = out.File
	file_osac_private_v1_network_class_type_proto_goTypes = nil
	file_osac_private_v1_network_class_type_proto_depIdxs = nil
}
