//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/organization_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for Organization resources.
//
// State transitions typically follow: UNSPECIFIED -> PENDING -> SYNCED, with FAILED as a terminal error state
// that may require user intervention or resource recreation.
type OrganizationState int32

const (
	// State is unknown or has not been determined yet. This is the default state before initialization.
	OrganizationState_ORGANIZATION_STATE_UNSPECIFIED OrganizationState = 0
	// The organization is being synchronized to the identity provider and is not ready for use yet.
	//
	// During this state, the system is:
	// - Creating an organization in the identity provider
	// - Creating the break-glass account
	// - Assigning IDP manager permissions
	//
	// Users cannot be added to organizations in PENDING state.
	OrganizationState_ORGANIZATION_STATE_PENDING OrganizationState = 1
	// The organization has been successfully synchronized to the identity provider and is fully operational.
	//
	// In this state:
	// - IDP organization exists and is configured
	// - Break-glass account is created and has proper permissions
	// - Users can be added to the organization
	// - The organization is ready for use
	OrganizationState_ORGANIZATION_STATE_SYNCED OrganizationState = 2
	// The organization synchronization to the IDP has failed and the organization is unusable.
	//
	// Common failure reasons include:
	// - IDP connection timeout or network issues
	// - Organization name already exists in the IDP
	// - Invalid organization name format (doesn't meet IDP requirements)
	// - IDP authentication or authorization failure
	// - Break-glass account creation failure
	//
	// The status.message field will contain specific error details. Failed organizations typically require deletion
	// and recreation with corrected parameters, or manual IDP cleanup.
	OrganizationState_ORGANIZATION_STATE_FAILED OrganizationState = 3
)

// Enum value maps for OrganizationState.
var (
	OrganizationState_name = map[int32]string{
		0: "ORGANIZATION_STATE_UNSPECIFIED",
		1: "ORGANIZATION_STATE_PENDING",
		2: "ORGANIZATION_STATE_SYNCED",
		3: "ORGANIZATION_STATE_FAILED",
	}
	OrganizationState_value = map[string]int32{
		"ORGANIZATION_STATE_UNSPECIFIED": 0,
		"ORGANIZATION_STATE_PENDING":     1,
		"ORGANIZATION_STATE_SYNCED":      2,
		"ORGANIZATION_STATE_FAILED":      3,
	}
)

func (x OrganizationState) Enum() *OrganizationState {
	p := new(OrganizationState)
	*p = x
	return p
}

func (x OrganizationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_organization_type_proto_enumTypes[0].Descriptor()
}

func (OrganizationState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_organization_type_proto_enumTypes[0]
}

func (x OrganizationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *OrganizationSpec      `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *OrganizationStatus    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_osac_private_v1_organization_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_organization_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Organization) GetSpec() *OrganizationSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Organization) GetStatus() *OrganizationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Organization) SetId(v string) {
	x.Id = v
}

func (x *Organization) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *Organization) SetSpec(v *OrganizationSpec) {
	x.Spec = v
}

func (x *Organization) SetStatus(v *OrganizationStatus) {
	x.Status = v
}

func (x *Organization) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Organization) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *Organization) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *Organization) ClearMetadata() {
	x.Metadata = nil
}

func (x *Organization) ClearSpec() {
	x.Spec = nil
}

func (x *Organization) ClearStatus() {
	x.Status = nil
}

type Organization_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       string
	Metadata *Metadata
	Spec     *OrganizationSpec
	Status   *OrganizationStatus
}

func (b0 Organization_builder) Build() *Organization {
	m0 := &Organization{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

type OrganizationSpec struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationSpec) Reset() {
	*x = OrganizationSpec{}
	mi := &file_osac_private_v1_organization_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSpec) ProtoMessage() {}

func (x *OrganizationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_organization_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type OrganizationSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 OrganizationSpec_builder) Build() *OrganizationSpec {
	m0 := &OrganizationSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Represents the current operational state of an Organization.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the system updates them
// based on the reconciliation with the identity provider.
type OrganizationStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Break-glass account credentials.
	// Only populated on successful creation. These credentials must be stored securely.
	// This field is not persisted and will be empty when reading existing organizations.
	BreakGlassCredentials *BreakGlassCredentials `protobuf:"bytes,1,opt,name=break_glass_credentials,json=breakGlassCredentials,proto3" json:"break_glass_credentials,omitempty"`
	// Current lifecycle state of the organization's IDP synchronization.
	State OrganizationState `protobuf:"varint,2,opt,name=state,proto3,enum=osac.private.v1.OrganizationState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, this might contain progress information like "Waiting for IDP sync" or
	// "Creating organization in identity provider".
	//
	// For FAILED state, this contains error details explaining what went wrong, such as "IDP connection timeout",
	// "Organization name already exists in IDP", or "Invalid organization name format".
	//
	// For SYNCED state, this is typically empty or contains confirmation like "Organization synced to IDP".
	Message *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Name of the organization created in the identity provider.
	// Different providers use different terminology (Keycloak: realm, Auth0: tenant, Okta: organization),
	// but this field generically stores the IDP-side organization identifier.
	// Typically matches the organization name but stored here for reference.
	// This is set by the controller after successful IDP sync.
	// Empty string when state is PENDING or FAILED.
	IdpOrganizationName string `protobuf:"bytes,4,opt,name=idp_organization_name,json=idpOrganizationName,proto3" json:"idp_organization_name,omitempty"`
	// User ID of the break-glass account created in the identity provider.
	// This account has limited administrative permissions for managing users and identity providers.
	// The break-glass password is NOT stored here for security reasons - it is only returned once
	// during organization creation.
	// Empty string when state is PENDING or FAILED.
	BreakGlassUserId string `protobuf:"bytes,5,opt,name=break_glass_user_id,json=breakGlassUserId,proto3" json:"break_glass_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrganizationStatus) Reset() {
	*x = OrganizationStatus{}
	mi := &file_osac_private_v1_organization_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationStatus) ProtoMessage() {}

func (x *OrganizationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_organization_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrganizationStatus) GetBreakGlassCredentials() *BreakGlassCredentials {
	if x != nil {
		return x.BreakGlassCredentials
	}
	return nil
}

func (x *OrganizationStatus) GetState() OrganizationState {
	if x != nil {
		return x.State
	}
	return OrganizationState_ORGANIZATION_STATE_UNSPECIFIED
}

func (x *OrganizationStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *OrganizationStatus) GetIdpOrganizationName() string {
	if x != nil {
		return x.IdpOrganizationName
	}
	return ""
}

func (x *OrganizationStatus) GetBreakGlassUserId() string {
	if x != nil {
		return x.BreakGlassUserId
	}
	return ""
}

func (x *OrganizationStatus) SetBreakGlassCredentials(v *BreakGlassCredentials) {
	x.BreakGlassCredentials = v
}

func (x *OrganizationStatus) SetState(v OrganizationState) {
	x.State = v
}

func (x *OrganizationStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *OrganizationStatus) SetIdpOrganizationName(v string) {
	x.IdpOrganizationName = v
}

func (x *OrganizationStatus) SetBreakGlassUserId(v string) {
	x.BreakGlassUserId = v
}

func (x *OrganizationStatus) HasBreakGlassCredentials() bool {
	if x == nil {
		return false
	}
	return x.BreakGlassCredentials != nil
}

func (x *OrganizationStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *OrganizationStatus) ClearBreakGlassCredentials() {
	x.BreakGlassCredentials = nil
}

func (x *OrganizationStatus) ClearMessage() {
	x.Message = nil
}

type OrganizationStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Break-glass account credentials.
	// Only populated on successful creation. These credentials must be stored securely.
	// This field is not persisted and will be empty when reading existing organizations.
	BreakGlassCredentials *BreakGlassCredentials
	// Current lifecycle state of the organization's IDP synchronization.
	State OrganizationState
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, this might contain progress information like "Waiting for IDP sync" or
	// "Creating organization in identity provider".
	//
	// For FAILED state, this contains error details explaining what went wrong, such as "IDP connection timeout",
	// "Organization name already exists in IDP", or "Invalid organization name format".
	//
	// For SYNCED state, this is typically empty or contains confirmation like "Organization synced to IDP".
	Message *string
	// Name of the organization created in the identity provider.
	// Different providers use different terminology (Keycloak: realm, Auth0: tenant, Okta: organization),
	// but this field generically stores the IDP-side organization identifier.
	// Typically matches the organization name but stored here for reference.
	// This is set by the controller after successful IDP sync.
	// Empty string when state is PENDING or FAILED.
	IdpOrganizationName string
	// User ID of the break-glass account created in the identity provider.
	// This account has limited administrative permissions for managing users and identity providers.
	// The break-glass password is NOT stored here for security reasons - it is only returned once
	// during organization creation.
	// Empty string when state is PENDING or FAILED.
	BreakGlassUserId string
}

func (b0 OrganizationStatus_builder) Build() *OrganizationStatus {
	m0 := &OrganizationStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.BreakGlassCredentials = b.BreakGlassCredentials
	x.State = b.State
	x.Message = b.Message
	x.IdpOrganizationName = b.IdpOrganizationName
	x.BreakGlassUserId = b.BreakGlassUserId
	return m0
}

var File_osac_private_v1_organization_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_organization_type_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x32, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x5f, 0x67, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x63, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70,
	0x65, 0x63, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x12, 0x0a, 0x10, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x70, 0x65, 0x63, 0x22, 0xbc, 0x02, 0x0a, 0x12, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x5e, 0x0a, 0x17, 0x62, 0x72,
	0x65, 0x61, 0x6b, 0x5f, 0x67, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x72,
	0x65, 0x61, 0x6b, 0x47, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x52, 0x15, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x47, 0x6c, 0x61, 0x73, 0x73, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x64, 0x70, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x69, 0x64, 0x70, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x13, 0x62, 0x72, 0x65, 0x61, 0x6b,
	0x5f, 0x67, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x47, 0x6c, 0x61, 0x73, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0x95, 0x01, 0x0a, 0x11, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x4f, 0x52, 0x47, 0x41,
	0x4e, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a,
	0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19,
	0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x4f,
	0x52, 0x47, 0x41, 0x4e, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xda, 0x01, 0x0a, 0x13, 0x63,
	0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x42, 0x15, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa,
	0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_organization_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_organization_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_organization_type_proto_goTypes = []any{
	(OrganizationState)(0),        // 0: osac.private.v1.OrganizationState
	(*Organization)(nil),          // 1: osac.private.v1.Organization
	(*OrganizationSpec)(nil),      // 2: osac.private.v1.OrganizationSpec
	(*OrganizationStatus)(nil),    // 3: osac.private.v1.OrganizationStatus
	(*Metadata)(nil),              // 4: osac.private.v1.Metadata
	(*BreakGlassCredentials)(nil), // 5: osac.private.v1.BreakGlassCredentials
}
var file_osac_private_v1_organization_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.Organization.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.Organization.spec:type_name -> osac.private.v1.OrganizationSpec
	3, // 2: osac.private.v1.Organization.status:type_name -> osac.private.v1.OrganizationStatus
	5, // 3: osac.private.v1.OrganizationStatus.break_glass_credentials:type_name -> osac.private.v1.BreakGlassCredentials
	0, // 4: osac.private.v1.OrganizationStatus.state:type_name -> osac.private.v1.OrganizationState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_organization_type_proto_init() }
func file_osac_private_v1_organization_type_proto_init() {
	if File_osac_private_v1_organization_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_break_glass_credentials_type_proto_init()
	file_osac_private_v1_organization_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_organization_type_proto_rawDesc), len(file_osac_private_v1_organization_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_organization_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_organization_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_organization_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_organization_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_organization_type_proto = out.File
	file_osac_private_v1_organization_type_proto_goTypes = nil
	file_osac_private_v1_organization_type_proto_depIdxs = nil
}
