//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/public_ip_type.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for PublicIP resources.
//
// State transitions follow the attachment lifecycle: UNSPECIFIED -> PENDING -> ALLOCATED -> ATTACHING -> ATTACHED -> RELEASING.
// A PublicIP in ATTACHED state can return to ALLOCATED when detached from its ComputeInstance.
// FAILED is a terminal state for provisioning or release failures.
type PublicIPState int32

const (
	// State is unknown or has not been determined yet. Default state before initialization.
	PublicIPState_PUBLIC_IP_STATE_UNSPECIFIED PublicIPState = 0
	// The public IP is being provisioned and an address has not been assigned yet.
	//
	// During this state, the system is creating the MetalLB LoadBalancer Service on the target
	// cluster and waiting for an IP address to be allocated from the parent pool's CIDR range.
	PublicIPState_PUBLIC_IP_STATE_PENDING PublicIPState = 1
	// The public IP has been assigned an address but is not attached to any ComputeInstance.
	//
	// The address is allocated and reserved. The IP can be attached to a ComputeInstance by
	// setting spec.compute_instance, which transitions it to ATTACHING. Detaching from an
	// instance returns the IP to this state.
	PublicIPState_PUBLIC_IP_STATE_ALLOCATED PublicIPState = 2
	// The public IP is being attached to a ComputeInstance.
	//
	// During this state, the system is moving the MetalLB LoadBalancer Service to bind the
	// allocated address to the target ComputeInstance. Once complete, the state transitions
	// to ATTACHED. Set immediately on successful Update validation when spec.compute_instance
	// is populated on an ALLOCATED PublicIP.
	PublicIPState_PUBLIC_IP_STATE_ATTACHING PublicIPState = 3
	// The public IP is attached to a ComputeInstance and actively routing traffic.
	//
	// The allocated address is bound to the ComputeInstance specified in spec.compute_instance.
	// Clearing the compute_instance field detaches the IP, transitioning through RELEASING
	// back to ALLOCATED.
	PublicIPState_PUBLIC_IP_STATE_ATTACHED PublicIPState = 4
	// The public IP is being released from its current ComputeInstance binding.
	//
	// On detach (clearing spec.compute_instance from an ATTACHED IP), the system unbinds
	// the address from the ComputeInstance. The address is preserved and the IP returns to
	// ALLOCATED once complete.
	PublicIPState_PUBLIC_IP_STATE_RELEASING PublicIPState = 5
	// Provisioning or release failed. Check status.message for error details.
	//
	// This is a terminal error state. The PublicIP may require manual intervention
	// (e.g., deleting and recreating) or a Signal RPC to retry the operation.
	PublicIPState_PUBLIC_IP_STATE_FAILED PublicIPState = 6
	// The public IP is being deprovisioned and will be removed.
	//
	// On deletion of an ALLOCATED PublicIP, the system removes the MetalLB LoadBalancer
	// Service and returns the address to the pool. Only ALLOCATED PublicIPs can be deleted.
	PublicIPState_PUBLIC_IP_STATE_DELETING PublicIPState = 7
)

// Enum value maps for PublicIPState.
var (
	PublicIPState_name = map[int32]string{
		0: "PUBLIC_IP_STATE_UNSPECIFIED",
		1: "PUBLIC_IP_STATE_PENDING",
		2: "PUBLIC_IP_STATE_ALLOCATED",
		3: "PUBLIC_IP_STATE_ATTACHING",
		4: "PUBLIC_IP_STATE_ATTACHED",
		5: "PUBLIC_IP_STATE_RELEASING",
		6: "PUBLIC_IP_STATE_FAILED",
		7: "PUBLIC_IP_STATE_DELETING",
	}
	PublicIPState_value = map[string]int32{
		"PUBLIC_IP_STATE_UNSPECIFIED": 0,
		"PUBLIC_IP_STATE_PENDING":     1,
		"PUBLIC_IP_STATE_ALLOCATED":   2,
		"PUBLIC_IP_STATE_ATTACHING":   3,
		"PUBLIC_IP_STATE_ATTACHED":    4,
		"PUBLIC_IP_STATE_RELEASING":   5,
		"PUBLIC_IP_STATE_FAILED":      6,
		"PUBLIC_IP_STATE_DELETING":    7,
	}
)

func (x PublicIPState) Enum() *PublicIPState {
	p := new(PublicIPState)
	*p = x
	return p
}

func (x PublicIPState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicIPState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_public_ip_type_proto_enumTypes[0].Descriptor()
}

func (PublicIPState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_public_ip_type_proto_enumTypes[0]
}

func (x PublicIPState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a public IP address allocated from a PublicIPPool.
//
// A PublicIP is a floating public IP address that can be optionally attached to a ComputeInstance.
// IPs are allocated from a parent PublicIPPool's CIDR ranges. The pool assignment is immutable
// after creation, while the compute_instance attachment can be changed to move the IP between
// instances.
//
// The lifecycle follows: PENDING (awaiting allocation) -> ALLOCATED (IP assigned, not attached) ->
// ATTACHING (binding to instance) -> ATTACHED (bound to a ComputeInstance).
// Detaching transitions through RELEASING back to ALLOCATED (address preserved).
// Deallocation also uses RELEASING, after which the address is returned to the pool.
type PublicIP struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the public IP.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the public IP, including name, labels, and timestamps.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired configuration of the public IP (user-specified).
	Spec *PublicIPSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current state of the public IP (system-provided, read-only).
	Status        *PublicIPStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIP) Reset() {
	*x = PublicIP{}
	mi := &file_osac_private_v1_public_ip_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIP) ProtoMessage() {}

func (x *PublicIP) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIP) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicIP) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublicIP) GetSpec() *PublicIPSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PublicIP) GetStatus() *PublicIPStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PublicIP) SetId(v string) {
	x.Id = v
}

func (x *PublicIP) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *PublicIP) SetSpec(v *PublicIPSpec) {
	x.Spec = v
}

func (x *PublicIP) SetStatus(v *PublicIPStatus) {
	x.Status = v
}

func (x *PublicIP) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *PublicIP) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *PublicIP) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *PublicIP) ClearMetadata() {
	x.Metadata = nil
}

func (x *PublicIP) ClearSpec() {
	x.Spec = nil
}

func (x *PublicIP) ClearStatus() {
	x.Status = nil
}

type PublicIP_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the public IP.
	Id string
	// Metadata of the public IP, including name, labels, and timestamps.
	Metadata *Metadata
	// Desired configuration of the public IP (user-specified).
	Spec *PublicIPSpec
	// Current state of the public IP (system-provided, read-only).
	Status *PublicIPStatus
}

func (b0 PublicIP_builder) Build() *PublicIP {
	m0 := &PublicIP{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the desired configuration for a PublicIP.
//
// The pool field is required and immutable: once a PublicIP is allocated from a pool, it cannot
// be moved to a different pool. The compute_instance field is optional and mutable, allowing the
// IP to be attached to or detached from ComputeInstances over its lifetime.
type PublicIPSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Parent PublicIPPool ID. Required and immutable after creation.
	//
	// Must reference the ID of an existing PublicIPPool in READY state. The system allocates an
	// available IP address from this pool's CIDR ranges during provisioning.
	//
	// Example: "pool-abc123"
	Pool string `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	// ComputeInstance ID to attach this public IP to. Optional.
	//
	// When set, the system binds this public IP to the specified ComputeInstance, making the
	// instance reachable at the allocated address. When cleared, the IP transitions through
	// RELEASING back to ALLOCATED (the address is retained but no longer routes to an instance).
	//
	// Example: "ci-xyz789"
	ComputeInstance *string `protobuf:"bytes,2,opt,name=compute_instance,json=computeInstance,proto3,oneof" json:"compute_instance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublicIPSpec) Reset() {
	*x = PublicIPSpec{}
	mi := &file_osac_private_v1_public_ip_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPSpec) ProtoMessage() {}

func (x *PublicIPSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPSpec) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *PublicIPSpec) GetComputeInstance() string {
	if x != nil && x.ComputeInstance != nil {
		return *x.ComputeInstance
	}
	return ""
}

func (x *PublicIPSpec) SetPool(v string) {
	x.Pool = v
}

func (x *PublicIPSpec) SetComputeInstance(v string) {
	x.ComputeInstance = &v
}

func (x *PublicIPSpec) HasComputeInstance() bool {
	if x == nil {
		return false
	}
	return x.ComputeInstance != nil
}

func (x *PublicIPSpec) ClearComputeInstance() {
	x.ComputeInstance = nil
}

type PublicIPSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Parent PublicIPPool ID. Required and immutable after creation.
	//
	// Must reference the ID of an existing PublicIPPool in READY state. The system allocates an
	// available IP address from this pool's CIDR ranges during provisioning.
	//
	// Example: "pool-abc123"
	Pool string
	// ComputeInstance ID to attach this public IP to. Optional.
	//
	// When set, the system binds this public IP to the specified ComputeInstance, making the
	// instance reachable at the allocated address. When cleared, the IP transitions through
	// RELEASING back to ALLOCATED (the address is retained but no longer routes to an instance).
	//
	// Example: "ci-xyz789"
	ComputeInstance *string
}

func (b0 PublicIPSpec_builder) Build() *PublicIPSpec {
	m0 := &PublicIPSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Pool = b.Pool
	x.ComputeInstance = b.ComputeInstance
	return m0
}

// Represents the current operational state of a PublicIP.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the system
// updates them based on reconciliation of the spec and feedback from the cluster controller.
type PublicIPStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the public IP.
	State PublicIPState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.PublicIPState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, may contain progress information like "Waiting for IP allocation".
	// For RELEASING state, may contain cleanup progress. Typically empty for ALLOCATED and
	// ATTACHED states.
	Message *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Identifier of the hub cluster that this public IP is deployed to.
	//
	// Set by the fulfillment-service controller when reconciling the public IP to a Kubernetes CR
	// on the target hub cluster. Used for tracking which cluster the IP resources reside on.
	Hub string `protobuf:"bytes,3,opt,name=hub,proto3" json:"hub,omitempty"`
	// Allocated IP address from the parent pool's CIDR range.
	//
	// Populated once the IP transitions to ALLOCATED state. Remains stable through ATTACHING,
	// ATTACHED, and RELEASING (detach). Cleared only when the IP is deallocated.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// Parent PublicIPPool ID that this IP was allocated from.
	//
	// Mirrors spec.pool for convenience in status queries. Populated when the IP is allocated.
	Pool          string `protobuf:"bytes,5,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPStatus) Reset() {
	*x = PublicIPStatus{}
	mi := &file_osac_private_v1_public_ip_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPStatus) ProtoMessage() {}

func (x *PublicIPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPStatus) GetState() PublicIPState {
	if x != nil {
		return x.State
	}
	return PublicIPState_PUBLIC_IP_STATE_UNSPECIFIED
}

func (x *PublicIPStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *PublicIPStatus) GetHub() string {
	if x != nil {
		return x.Hub
	}
	return ""
}

func (x *PublicIPStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PublicIPStatus) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *PublicIPStatus) SetState(v PublicIPState) {
	x.State = v
}

func (x *PublicIPStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *PublicIPStatus) SetHub(v string) {
	x.Hub = v
}

func (x *PublicIPStatus) SetAddress(v string) {
	x.Address = v
}

func (x *PublicIPStatus) SetPool(v string) {
	x.Pool = v
}

func (x *PublicIPStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *PublicIPStatus) ClearMessage() {
	x.Message = nil
}

type PublicIPStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the public IP.
	State PublicIPState
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, may contain progress information like "Waiting for IP allocation".
	// For RELEASING state, may contain cleanup progress. Typically empty for ALLOCATED and
	// ATTACHED states.
	Message *string
	// Identifier of the hub cluster that this public IP is deployed to.
	//
	// Set by the fulfillment-service controller when reconciling the public IP to a Kubernetes CR
	// on the target hub cluster. Used for tracking which cluster the IP resources reside on.
	Hub string
	// Allocated IP address from the parent pool's CIDR range.
	//
	// Populated once the IP transitions to ALLOCATED state. Remains stable through ATTACHING,
	// ATTACHED, and RELEASING (detach). Cleared only when the IP is deallocated.
	Address string
	// Parent PublicIPPool ID that this IP was allocated from.
	//
	// Mirrors spec.pool for convenience in status queries. Populated when the IP is allocated.
	Pool string
}

func (b0 PublicIPStatus_builder) Build() *PublicIPStatus {
	m0 := &PublicIPStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	x.Hub = b.Hub
	x.Address = b.Address
	x.Pool = b.Pool
	return m0
}

var File_osac_private_v1_public_ip_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_public_ip_type_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x01,
	0x0a, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6f, 0x0a,
	0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a,
	0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe0, 0x41, 0x02,
	0xe0, 0x41, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x12, 0x2e, 0x0a, 0x10, 0x63, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0xca,
	0x01, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1e, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0,
	0x41, 0x03, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x15, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0,
	0x41, 0x03, 0x52, 0x03, 0x68, 0x75, 0x62, 0x12, 0x1d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x82, 0x02, 0x0a, 0x0d,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a,
	0x1b, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b,
	0x0a, 0x17, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x50,
	0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41,
	0x4c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x54,
	0x54, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x55, 0x42,
	0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x54, 0x54,
	0x41, 0x43, 0x48, 0x45, 0x44, 0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x55, 0x42, 0x4c, 0x49,
	0x43, 0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x4c, 0x45, 0x41,
	0x53, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43,
	0x5f, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x06, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x07,
	0x42, 0xd6, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x70, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50,
	0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var file_osac_private_v1_public_ip_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_public_ip_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_public_ip_type_proto_goTypes = []any{
	(PublicIPState)(0),     // 0: osac.private.v1.PublicIPState
	(*PublicIP)(nil),       // 1: osac.private.v1.PublicIP
	(*PublicIPSpec)(nil),   // 2: osac.private.v1.PublicIPSpec
	(*PublicIPStatus)(nil), // 3: osac.private.v1.PublicIPStatus
	(*Metadata)(nil),       // 4: osac.private.v1.Metadata
}
var file_osac_private_v1_public_ip_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.PublicIP.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.PublicIP.spec:type_name -> osac.private.v1.PublicIPSpec
	3, // 2: osac.private.v1.PublicIP.status:type_name -> osac.private.v1.PublicIPStatus
	0, // 3: osac.private.v1.PublicIPStatus.state:type_name -> osac.private.v1.PublicIPState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_public_ip_type_proto_init() }
func file_osac_private_v1_public_ip_type_proto_init() {
	if File_osac_private_v1_public_ip_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_public_ip_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_osac_private_v1_public_ip_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_public_ip_type_proto_rawDesc), len(file_osac_private_v1_public_ip_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_public_ip_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_public_ip_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_public_ip_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_public_ip_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_public_ip_type_proto = out.File
	file_osac_private_v1_public_ip_type_proto_goTypes = nil
	file_osac_private_v1_public_ip_type_proto_depIdxs = nil
}
