//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/public_ip_attachment_type.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for PublicIPAttachment resources.
//
// State transitions: UNSPECIFIED -> PENDING -> READY. On deletion: any state -> DELETING.
// FAILED can occur from PENDING and retries automatically via the provisioning lifecycle.
type PublicIPAttachmentState int32

const (
	// State is unknown or has not been determined yet.
	PublicIPAttachmentState_PUBLIC_IP_ATTACHMENT_STATE_UNSPECIFIED PublicIPAttachmentState = 0
	// The attachment is being provisioned (attach AAP job in progress).
	//
	// The system is binding the PublicIP's allocated address to the target resource. This
	// involves creating the MetalLB LoadBalancer Service in the target's namespace and
	// configuring routing.
	PublicIPAttachmentState_PUBLIC_IP_ATTACHMENT_STATE_PENDING PublicIPAttachmentState = 1
	// The attachment is active and the target is reachable via the public IP address.
	//
	// The PublicIP's allocated address is bound to the target resource and actively routing
	// traffic. The parent PublicIP's status.attached is set to true.
	PublicIPAttachmentState_PUBLIC_IP_ATTACHMENT_STATE_READY PublicIPAttachmentState = 2
	// The attachment failed. Check status.message for error details.
	//
	// The provisioning lifecycle retries automatically with exponential backoff. Unlike the
	// previous inline attach/detach model, failed attachments do not create dead ends.
	PublicIPAttachmentState_PUBLIC_IP_ATTACHMENT_STATE_FAILED PublicIPAttachmentState = 3
	// The attachment is being deprovisioned (detach AAP job in progress).
	//
	// Triggered by deletion of the PublicIPAttachment resource. The system unbinds the
	// address from the target and moves the MetalLB Service back to the parking namespace.
	// On completion, the parent PublicIP's status.attached is set to false.
	PublicIPAttachmentState_PUBLIC_IP_ATTACHMENT_STATE_DELETING PublicIPAttachmentState = 4
)

// Enum value maps for PublicIPAttachmentState.
var (
	PublicIPAttachmentState_name = map[int32]string{
		0: "PUBLIC_IP_ATTACHMENT_STATE_UNSPECIFIED",
		1: "PUBLIC_IP_ATTACHMENT_STATE_PENDING",
		2: "PUBLIC_IP_ATTACHMENT_STATE_READY",
		3: "PUBLIC_IP_ATTACHMENT_STATE_FAILED",
		4: "PUBLIC_IP_ATTACHMENT_STATE_DELETING",
	}
	PublicIPAttachmentState_value = map[string]int32{
		"PUBLIC_IP_ATTACHMENT_STATE_UNSPECIFIED": 0,
		"PUBLIC_IP_ATTACHMENT_STATE_PENDING":     1,
		"PUBLIC_IP_ATTACHMENT_STATE_READY":       2,
		"PUBLIC_IP_ATTACHMENT_STATE_FAILED":      3,
		"PUBLIC_IP_ATTACHMENT_STATE_DELETING":    4,
	}
)

func (x PublicIPAttachmentState) Enum() *PublicIPAttachmentState {
	p := new(PublicIPAttachmentState)
	*p = x
	return p
}

func (x PublicIPAttachmentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicIPAttachmentState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_public_ip_attachment_type_proto_enumTypes[0].Descriptor()
}

func (PublicIPAttachmentState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_public_ip_attachment_type_proto_enumTypes[0]
}

func (x PublicIPAttachmentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a binding between a PublicIP and a target resource (e.g., a ComputeInstance).
//
// A PublicIPAttachment is a first-class resource that manages the attach/detach lifecycle
// independently from the PublicIP allocation lifecycle. Creating a PublicIPAttachment triggers
// the attach workflow; deleting it triggers the detach workflow.
//
// The binding is immutable: to change the target, delete the attachment and create a new one.
// The oneof target field supports future target types (Cluster, BareMetalServer) without
// breaking changes.
//
// Lifecycle: PENDING (attach in progress) -> READY (attached and routing traffic) -> DELETING
// (detach in progress). FAILED is a terminal error state that retries via the standard
// provisioning lifecycle with exponential backoff.
type PublicIPAttachment struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the public IP attachment.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the public IP attachment, including name, labels, and timestamps.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired configuration of the public IP attachment (user-specified).
	Spec *PublicIPAttachmentSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current state of the public IP attachment (system-provided, read-only).
	Status        *PublicIPAttachmentStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPAttachment) Reset() {
	*x = PublicIPAttachment{}
	mi := &file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPAttachment) ProtoMessage() {}

func (x *PublicIPAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPAttachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicIPAttachment) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublicIPAttachment) GetSpec() *PublicIPAttachmentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PublicIPAttachment) GetStatus() *PublicIPAttachmentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PublicIPAttachment) SetId(v string) {
	x.Id = v
}

func (x *PublicIPAttachment) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *PublicIPAttachment) SetSpec(v *PublicIPAttachmentSpec) {
	x.Spec = v
}

func (x *PublicIPAttachment) SetStatus(v *PublicIPAttachmentStatus) {
	x.Status = v
}

func (x *PublicIPAttachment) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *PublicIPAttachment) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *PublicIPAttachment) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *PublicIPAttachment) ClearMetadata() {
	x.Metadata = nil
}

func (x *PublicIPAttachment) ClearSpec() {
	x.Spec = nil
}

func (x *PublicIPAttachment) ClearStatus() {
	x.Status = nil
}

type PublicIPAttachment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the public IP attachment.
	Id string
	// Metadata of the public IP attachment, including name, labels, and timestamps.
	Metadata *Metadata
	// Desired configuration of the public IP attachment (user-specified).
	Spec *PublicIPAttachmentSpec
	// Current state of the public IP attachment (system-provided, read-only).
	Status *PublicIPAttachmentStatus
}

func (b0 PublicIPAttachment_builder) Build() *PublicIPAttachment {
	m0 := &PublicIPAttachment{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the desired configuration for a PublicIPAttachment.
//
// Both fields are required and immutable after creation. The public_ip must reference an
// existing PublicIP in ALLOCATED state. The target must reference a valid resource that
// supports public IP attachment.
type PublicIPAttachmentSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// PublicIP ID to attach. Required and immutable after creation.
	//
	// Must reference the ID of an existing PublicIP in ALLOCATED state that is not already
	// attached (status.attached == false). Only one PublicIPAttachment may exist per PublicIP.
	//
	// Example: "019728a4-3f5c-7def-8abc-1234567890ab"
	PublicIp string `protobuf:"bytes,1,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	// Target resource to attach the public IP to. Exactly one target field must be set.
	// Required and immutable after creation.
	//
	// Types that are valid to be assigned to Target:
	//
	//	*PublicIPAttachmentSpec_ComputeInstance
	Target        isPublicIPAttachmentSpec_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPAttachmentSpec) Reset() {
	*x = PublicIPAttachmentSpec{}
	mi := &file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPAttachmentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPAttachmentSpec) ProtoMessage() {}

func (x *PublicIPAttachmentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPAttachmentSpec) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *PublicIPAttachmentSpec) GetTarget() isPublicIPAttachmentSpec_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PublicIPAttachmentSpec) GetComputeInstance() string {
	if x != nil {
		if x, ok := x.Target.(*PublicIPAttachmentSpec_ComputeInstance); ok {
			return x.ComputeInstance
		}
	}
	return ""
}

func (x *PublicIPAttachmentSpec) SetPublicIp(v string) {
	x.PublicIp = v
}

func (x *PublicIPAttachmentSpec) SetComputeInstance(v string) {
	x.Target = &PublicIPAttachmentSpec_ComputeInstance{v}
}

func (x *PublicIPAttachmentSpec) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.Target != nil
}

func (x *PublicIPAttachmentSpec) HasComputeInstance() bool {
	if x == nil {
		return false
	}
	_, ok := x.Target.(*PublicIPAttachmentSpec_ComputeInstance)
	return ok
}

func (x *PublicIPAttachmentSpec) ClearTarget() {
	x.Target = nil
}

func (x *PublicIPAttachmentSpec) ClearComputeInstance() {
	if _, ok := x.Target.(*PublicIPAttachmentSpec_ComputeInstance); ok {
		x.Target = nil
	}
}

const PublicIPAttachmentSpec_Target_not_set_case case_PublicIPAttachmentSpec_Target = 0
const PublicIPAttachmentSpec_ComputeInstance_case case_PublicIPAttachmentSpec_Target = 2

func (x *PublicIPAttachmentSpec) WhichTarget() case_PublicIPAttachmentSpec_Target {
	if x == nil {
		return PublicIPAttachmentSpec_Target_not_set_case
	}
	switch x.Target.(type) {
	case *PublicIPAttachmentSpec_ComputeInstance:
		return PublicIPAttachmentSpec_ComputeInstance_case
	default:
		return PublicIPAttachmentSpec_Target_not_set_case
	}
}

type PublicIPAttachmentSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// PublicIP ID to attach. Required and immutable after creation.
	//
	// Must reference the ID of an existing PublicIP in ALLOCATED state that is not already
	// attached (status.attached == false). Only one PublicIPAttachment may exist per PublicIP.
	//
	// Example: "019728a4-3f5c-7def-8abc-1234567890ab"
	PublicIp string
	// Target resource to attach the public IP to. Exactly one target field must be set.
	// Required and immutable after creation.

	// Fields of oneof Target:
	// ComputeInstance ID to attach this public IP to.
	//
	// Must reference the ID of an existing ComputeInstance in RUNNING state. Only one
	// PublicIPAttachment may exist per ComputeInstance.
	//
	// Example: "01972f1b-a4e9-7c82-9def-abcdef123456"
	ComputeInstance *string
	// -- end of Target
}

func (b0 PublicIPAttachmentSpec_builder) Build() *PublicIPAttachmentSpec {
	m0 := &PublicIPAttachmentSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.PublicIp = b.PublicIp
	if b.ComputeInstance != nil {
		x.Target = &PublicIPAttachmentSpec_ComputeInstance{*b.ComputeInstance}
	}
	return m0
}

type case_PublicIPAttachmentSpec_Target protoreflect.FieldNumber

func (x case_PublicIPAttachmentSpec_Target) String() string {
	md := file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPublicIPAttachmentSpec_Target interface {
	isPublicIPAttachmentSpec_Target()
}

type PublicIPAttachmentSpec_ComputeInstance struct {
	// ComputeInstance ID to attach this public IP to.
	//
	// Must reference the ID of an existing ComputeInstance in RUNNING state. Only one
	// PublicIPAttachment may exist per ComputeInstance.
	//
	// Example: "01972f1b-a4e9-7c82-9def-abcdef123456"
	ComputeInstance string `protobuf:"bytes,2,opt,name=compute_instance,json=computeInstance,proto3,oneof"`
}

func (*PublicIPAttachmentSpec_ComputeInstance) isPublicIPAttachmentSpec_Target() {}

// Represents the current operational state of a PublicIPAttachment.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the
// system updates them based on reconciliation of the spec and feedback from the cluster
// controller.
type PublicIPAttachmentStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the public IP attachment.
	State PublicIPAttachmentState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.PublicIPAttachmentState" json:"state,omitempty"`
	// Allocated IP address from the parent PublicIP.
	//
	// Populated for convenience once the attachment reaches READY state. Mirrors the address
	// field from the referenced PublicIP's status.
	PublicIpAddress string `protobuf:"bytes,2,opt,name=public_ip_address,json=publicIpAddress,proto3" json:"public_ip_address,omitempty"`
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, may contain progress information. For FAILED state, contains the
	// error details. Typically empty for READY state.
	Message *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Identifier of the hub cluster that this public IP attachment is deployed to.
	//
	// Set by the fulfillment-service controller when reconciling the attachment to a
	// Kubernetes CR on the target hub cluster.
	Hub           string `protobuf:"bytes,4,opt,name=hub,proto3" json:"hub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPAttachmentStatus) Reset() {
	*x = PublicIPAttachmentStatus{}
	mi := &file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPAttachmentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPAttachmentStatus) ProtoMessage() {}

func (x *PublicIPAttachmentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPAttachmentStatus) GetState() PublicIPAttachmentState {
	if x != nil {
		return x.State
	}
	return PublicIPAttachmentState_PUBLIC_IP_ATTACHMENT_STATE_UNSPECIFIED
}

func (x *PublicIPAttachmentStatus) GetPublicIpAddress() string {
	if x != nil {
		return x.PublicIpAddress
	}
	return ""
}

func (x *PublicIPAttachmentStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *PublicIPAttachmentStatus) GetHub() string {
	if x != nil {
		return x.Hub
	}
	return ""
}

func (x *PublicIPAttachmentStatus) SetState(v PublicIPAttachmentState) {
	x.State = v
}

func (x *PublicIPAttachmentStatus) SetPublicIpAddress(v string) {
	x.PublicIpAddress = v
}

func (x *PublicIPAttachmentStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *PublicIPAttachmentStatus) SetHub(v string) {
	x.Hub = v
}

func (x *PublicIPAttachmentStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *PublicIPAttachmentStatus) ClearMessage() {
	x.Message = nil
}

type PublicIPAttachmentStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the public IP attachment.
	State PublicIPAttachmentState
	// Allocated IP address from the parent PublicIP.
	//
	// Populated for convenience once the attachment reaches READY state. Mirrors the address
	// field from the referenced PublicIP's status.
	PublicIpAddress string
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, may contain progress information. For FAILED state, contains the
	// error details. Typically empty for READY state.
	Message *string
	// Identifier of the hub cluster that this public IP attachment is deployed to.
	//
	// Set by the fulfillment-service controller when reconciling the attachment to a
	// Kubernetes CR on the target hub cluster.
	Hub string
}

func (b0 PublicIPAttachmentStatus_builder) Build() *PublicIPAttachmentStatus {
	m0 := &PublicIPAttachmentStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.PublicIpAddress = b.PublicIpAddress
	x.Message = b.Message
	x.Hub = b.Hub
	return m0
}

var File_osac_private_v1_public_ip_attachment_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_public_ip_attachment_type_proto_rawDesc = string([]byte{
	0x0a, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x49, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x74, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x23, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x06, 0xe0, 0x41, 0x02, 0xe0, 0x41, 0x05, 0x52, 0x08, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x49, 0x70, 0x12, 0x2b, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0xd7, 0x01, 0x0a,
	0x18, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x43, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2f,
	0x0a, 0x11, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x0f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x22, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x03, 0xe0, 0x41, 0x03, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x03, 0x68, 0x75, 0x62, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xe3, 0x01, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x2a, 0x0a, 0x26, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f,
	0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x26,
	0x0a, 0x22, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x41, 0x54, 0x54, 0x41,
	0x43, 0x48, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43,
	0x5f, 0x49, 0x50, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x25, 0x0a, 0x21,
	0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48,
	0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x27, 0x0a, 0x23, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50,
	0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x42, 0xe0, 0x01, 0x0a,
	0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x42, 0x1b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x70, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f,
	0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73,
	0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_public_ip_attachment_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_public_ip_attachment_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_public_ip_attachment_type_proto_goTypes = []any{
	(PublicIPAttachmentState)(0),     // 0: osac.private.v1.PublicIPAttachmentState
	(*PublicIPAttachment)(nil),       // 1: osac.private.v1.PublicIPAttachment
	(*PublicIPAttachmentSpec)(nil),   // 2: osac.private.v1.PublicIPAttachmentSpec
	(*PublicIPAttachmentStatus)(nil), // 3: osac.private.v1.PublicIPAttachmentStatus
	(*Metadata)(nil),                 // 4: osac.private.v1.Metadata
}
var file_osac_private_v1_public_ip_attachment_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.PublicIPAttachment.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.PublicIPAttachment.spec:type_name -> osac.private.v1.PublicIPAttachmentSpec
	3, // 2: osac.private.v1.PublicIPAttachment.status:type_name -> osac.private.v1.PublicIPAttachmentStatus
	0, // 3: osac.private.v1.PublicIPAttachmentStatus.state:type_name -> osac.private.v1.PublicIPAttachmentState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_public_ip_attachment_type_proto_init() }
func file_osac_private_v1_public_ip_attachment_type_proto_init() {
	if File_osac_private_v1_public_ip_attachment_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[1].OneofWrappers = []any{
		(*PublicIPAttachmentSpec_ComputeInstance)(nil),
	}
	file_osac_private_v1_public_ip_attachment_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_public_ip_attachment_type_proto_rawDesc), len(file_osac_private_v1_public_ip_attachment_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_public_ip_attachment_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_public_ip_attachment_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_public_ip_attachment_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_public_ip_attachment_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_public_ip_attachment_type_proto = out.File
	file_osac_private_v1_public_ip_attachment_type_proto_goTypes = nil
	file_osac_private_v1_public_ip_attachment_type_proto_depIdxs = nil
}
