//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/security_group_type.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Network protocol types for SecurityRule matching.
//
// Determines which layer 4 protocol the rule applies to. Protocol affects whether port range fields are
// applicable (TCP/UDP) or ignored (ICMP/ALL).
type Protocol int32

const (
	// Unknown protocol (invalid). This should never be used in actual rules.
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	// TCP protocol. Port ranges (port_from, port_to) are required for TCP rules.
	//
	// Used for connection-oriented protocols like HTTP, HTTPS, SSH, database connections, etc.
	Protocol_PROTOCOL_TCP Protocol = 1
	// UDP protocol. Port ranges (port_from, port_to) are required for UDP rules.
	//
	// Used for connectionless protocols like DNS, NTP, DHCP, VoIP, etc.
	Protocol_PROTOCOL_UDP Protocol = 2
	// ICMP protocol (ping and other control messages). Port ranges are not applicable.
	//
	// Used for network diagnostics (ping), error reporting, and control messages.
	Protocol_PROTOCOL_ICMP Protocol = 3
	// All protocols (wildcard). Port ranges are not applicable.
	//
	// Matches any protocol. Useful for allowing all traffic from a trusted CIDR block or for egress rules
	// that permit all outbound traffic.
	Protocol_PROTOCOL_ALL Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
		3: "PROTOCOL_ICMP",
		4: "PROTOCOL_ALL",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
		"PROTOCOL_ICMP":        3,
		"PROTOCOL_ALL":         4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_security_group_type_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_osac_private_v1_security_group_type_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Lifecycle states for SecurityGroup resources.
//
// State transitions typically follow: UNSPECIFIED -> PENDING -> READY, with FAILED as a terminal error state
// that may require user intervention or resource recreation.
type SecurityGroupState int32

const (
	// State is unknown or has not been determined yet. This is the default state before initialization.
	SecurityGroupState_SECURITY_GROUP_STATE_UNSPECIFIED SecurityGroupState = 0
	// The security group is being initialized and is not ready for use yet.
	//
	// During this state, the system is:
	// - Validating firewall rules (port ranges, CIDR notation)
	// - Checking parent VirtualNetwork exists and is in READY state
	// - Configuring firewall backend
	// - Installing rules in the network infrastructure
	//
	// Security groups in PENDING state cannot be attached to compute instances.
	SecurityGroupState_SECURITY_GROUP_STATE_PENDING SecurityGroupState = 1
	// The security group is fully operational and ready for compute instances to use.
	//
	// In this state:
	// - All rules are validated and active
	// - Firewall backend is configured
	// - Security group can be attached to compute instances
	// - Traffic filtering is enforced according to the rules
	SecurityGroupState_SECURITY_GROUP_STATE_READY SecurityGroupState = 2
	// The security group has encountered an error and is unusable.
	//
	// Common failure reasons include:
	// - Invalid port range (port_from > port_to, or values outside 1-65535)
	// - Invalid CIDR notation
	// - Parent VirtualNetwork does not exist
	// - Parent VirtualNetwork is not in READY state
	// - Protocol tcp/udp missing required port fields
	// - Firewall backend configuration error
	//
	// The status.message field will contain specific error details. Failed security groups typically require
	// deletion and recreation with corrected parameters, or resolution of the parent VirtualNetwork issue.
	SecurityGroupState_SECURITY_GROUP_STATE_FAILED SecurityGroupState = 3
	// The security group is being deleted.
	//
	// During this state, the system is:
	// - Removing firewall rules from the network infrastructure
	// - Cleaning up backend security group resources
	// - Processing deprovisioning jobs
	//
	// The security group will be archived once deletion completes successfully.
	SecurityGroupState_SECURITY_GROUP_STATE_DELETING SecurityGroupState = 4
	// The security group deletion has failed.
	//
	// The deprovision operation encountered an error and could not complete.
	// The status.message field will contain specific error details.
	// Manual intervention may be required to resolve the underlying issue
	// before retrying deletion.
	SecurityGroupState_SECURITY_GROUP_STATE_DELETE_FAILED SecurityGroupState = 5
)

// Enum value maps for SecurityGroupState.
var (
	SecurityGroupState_name = map[int32]string{
		0: "SECURITY_GROUP_STATE_UNSPECIFIED",
		1: "SECURITY_GROUP_STATE_PENDING",
		2: "SECURITY_GROUP_STATE_READY",
		3: "SECURITY_GROUP_STATE_FAILED",
		4: "SECURITY_GROUP_STATE_DELETING",
		5: "SECURITY_GROUP_STATE_DELETE_FAILED",
	}
	SecurityGroupState_value = map[string]int32{
		"SECURITY_GROUP_STATE_UNSPECIFIED":   0,
		"SECURITY_GROUP_STATE_PENDING":       1,
		"SECURITY_GROUP_STATE_READY":         2,
		"SECURITY_GROUP_STATE_FAILED":        3,
		"SECURITY_GROUP_STATE_DELETING":      4,
		"SECURITY_GROUP_STATE_DELETE_FAILED": 5,
	}
)

func (x SecurityGroupState) Enum() *SecurityGroupState {
	p := new(SecurityGroupState)
	*p = x
	return p
}

func (x SecurityGroupState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityGroupState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_security_group_type_proto_enumTypes[1].Descriptor()
}

func (SecurityGroupState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_security_group_type_proto_enumTypes[1]
}

func (x SecurityGroupState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a virtual firewall controlling network traffic for compute instances.
//
// SecurityGroup acts as a stateful firewall that controls inbound (ingress) and outbound (egress) traffic for
// compute instances within a VirtualNetwork. Rules are stateful, meaning return traffic is automatically allowed
// for established connections.
//
// SecurityGroups follow a default-deny policy: if no rules match, traffic is blocked. This ensures secure-by-default
// behavior where only explicitly allowed traffic can pass through.
//
// SecurityGroups are scoped to a VirtualNetwork and can be attached to multiple compute instances within that
// network. They cannot be used across different VirtualNetworks.
//
// The parent VirtualNetwork relationship is established via metadata.annotations using the 'osac.openshift.io/owner-reference'
// key with the VirtualNetwork ID as the value. This enables proper resource hierarchy for garbage collection - when
// a VirtualNetwork is deleted, all associated SecurityGroups are automatically cleaned up.
//
// Design follows AWS Security Groups and Azure Network Security Groups (NSGs) patterns, adapted for cloud-native
// multi-tenant environments.
type SecurityGroup struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the security group.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the security group, including name, labels, tenant, and timestamps.
	//
	// The parent VirtualNetwork relationship should be specified via metadata.annotations using the
	// 'osac.openshift.io/owner-reference' key with the VirtualNetwork ID as the value. This establishes resource
	// hierarchy for garbage collection.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired configuration of the security group (user-modifiable).
	Spec *SecurityGroupSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current state of the security group (system-provided, read-only).
	Status        *SecurityGroupStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityGroup) Reset() {
	*x = SecurityGroup{}
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityGroup) ProtoMessage() {}

func (x *SecurityGroup) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityGroup) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SecurityGroup) GetSpec() *SecurityGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *SecurityGroup) GetStatus() *SecurityGroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SecurityGroup) SetId(v string) {
	x.Id = v
}

func (x *SecurityGroup) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *SecurityGroup) SetSpec(v *SecurityGroupSpec) {
	x.Spec = v
}

func (x *SecurityGroup) SetStatus(v *SecurityGroupStatus) {
	x.Status = v
}

func (x *SecurityGroup) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *SecurityGroup) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *SecurityGroup) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *SecurityGroup) ClearMetadata() {
	x.Metadata = nil
}

func (x *SecurityGroup) ClearSpec() {
	x.Spec = nil
}

func (x *SecurityGroup) ClearStatus() {
	x.Status = nil
}

type SecurityGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the security group.
	Id string
	// Metadata of the security group, including name, labels, tenant, and timestamps.
	//
	// The parent VirtualNetwork relationship should be specified via metadata.annotations using the
	// 'osac.openshift.io/owner-reference' key with the VirtualNetwork ID as the value. This establishes resource
	// hierarchy for garbage collection.
	Metadata *Metadata
	// Desired configuration of the security group (user-modifiable).
	Spec *SecurityGroupSpec
	// Current state of the security group (system-provided, read-only).
	Status *SecurityGroupStatus
}

func (b0 SecurityGroup_builder) Build() *SecurityGroup {
	m0 := &SecurityGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the desired configuration for a SecurityGroup.
//
// The spec contains user-specified firewall rules that define allowed network traffic. Rules are evaluated
// in order, and the first matching rule determines whether traffic is allowed. If no rules match, traffic
// is denied by default.
type SecurityGroupSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Parent VirtualNetwork ID for this security group.
	//
	// Must reference the ID of an existing VirtualNetwork in READY state. Security groups are scoped to a
	// VirtualNetwork and can only be applied to compute instances within that network. This field is required
	// and immutable after creation.
	//
	// Example: "vnet-12345abc"
	VirtualNetwork string `protobuf:"bytes,1,opt,name=virtual_network,json=virtualNetwork,proto3" json:"virtual_network,omitempty"`
	// List of rules controlling inbound traffic to compute instances.
	//
	// Rules are evaluated in order; first matching rule determines whether traffic is allowed. If no rules
	// match, traffic is denied by default.
	//
	// Example: Allow SSH from specific CIDR, allow HTTP/HTTPS from anywhere, allow ICMP ping
	Ingress []*SecurityRule `protobuf:"bytes,2,rep,name=ingress,proto3" json:"ingress,omitempty"`
	// List of rules controlling outbound traffic from compute instances.
	//
	// Rules are evaluated in order; first matching rule determines whether traffic is allowed. If no rules
	// match, traffic is denied by default.
	//
	// Example: Allow all outbound traffic, or restrict to specific destinations
	Egress        []*SecurityRule `protobuf:"bytes,3,rep,name=egress,proto3" json:"egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityGroupSpec) Reset() {
	*x = SecurityGroupSpec{}
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityGroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityGroupSpec) ProtoMessage() {}

func (x *SecurityGroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityGroupSpec) GetVirtualNetwork() string {
	if x != nil {
		return x.VirtualNetwork
	}
	return ""
}

func (x *SecurityGroupSpec) GetIngress() []*SecurityRule {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *SecurityGroupSpec) GetEgress() []*SecurityRule {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *SecurityGroupSpec) SetVirtualNetwork(v string) {
	x.VirtualNetwork = v
}

func (x *SecurityGroupSpec) SetIngress(v []*SecurityRule) {
	x.Ingress = v
}

func (x *SecurityGroupSpec) SetEgress(v []*SecurityRule) {
	x.Egress = v
}

type SecurityGroupSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Parent VirtualNetwork ID for this security group.
	//
	// Must reference the ID of an existing VirtualNetwork in READY state. Security groups are scoped to a
	// VirtualNetwork and can only be applied to compute instances within that network. This field is required
	// and immutable after creation.
	//
	// Example: "vnet-12345abc"
	VirtualNetwork string
	// List of rules controlling inbound traffic to compute instances.
	//
	// Rules are evaluated in order; first matching rule determines whether traffic is allowed. If no rules
	// match, traffic is denied by default.
	//
	// Example: Allow SSH from specific CIDR, allow HTTP/HTTPS from anywhere, allow ICMP ping
	Ingress []*SecurityRule
	// List of rules controlling outbound traffic from compute instances.
	//
	// Rules are evaluated in order; first matching rule determines whether traffic is allowed. If no rules
	// match, traffic is denied by default.
	//
	// Example: Allow all outbound traffic, or restrict to specific destinations
	Egress []*SecurityRule
}

func (b0 SecurityGroupSpec_builder) Build() *SecurityGroupSpec {
	m0 := &SecurityGroupSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.VirtualNetwork = b.VirtualNetwork
	x.Ingress = b.Ingress
	x.Egress = b.Egress
	return m0
}

// Defines a single firewall rule for network traffic filtering.
//
// SecurityRule specifies which traffic to allow based on protocol, port ranges (for TCP/UDP), and source/
// destination CIDR blocks. Rules are stateful - return traffic for established connections is automatically
// allowed.
//
// Port ranges apply only to TCP and UDP protocols. For ICMP and ALL protocols, port fields are ignored.
//
// CIDR fields support IPv4-only, IPv6-only, or dual-stack configurations:
// - IPv4-only: Set ipv4_cidr, leave ipv6_cidr empty
// - IPv6-only: Set ipv6_cidr, leave ipv4_cidr empty
// - Dual-stack: Set both ipv4_cidr and ipv6_cidr (creates two separate rules internally)
type SecurityRule struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Protocol to match for this rule.
	//
	// Use PROTOCOL_ALL to match all protocols (wildcard). Use PROTOCOL_TCP or PROTOCOL_UDP when port ranges
	// are needed. Use PROTOCOL_ICMP for ping and other ICMP traffic.
	Protocol Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=osac.private.v1.Protocol" json:"protocol,omitempty"`
	// Starting port number for the rule (1-65535).
	//
	// Required for tcp/udp protocols, ignored for icmp/all. For single port, set port_from = port_to.
	// Must be <= port_to. Validation enforced at service layer.
	//
	// Example: 22 (SSH), 80 (HTTP), 443 (HTTPS), 3306 (MySQL)
	PortFrom *int32 `protobuf:"varint,2,opt,name=port_from,json=portFrom,proto3,oneof" json:"port_from,omitempty"`
	// Ending port number for the rule (1-65535).
	//
	// Required for tcp/udp protocols, ignored for icmp/all. Must be >= port_from. For single port, set
	// port_from = port_to. Validation enforced at service layer.
	//
	// Example: 22 (single port), 8000 (range 8000-9000)
	PortTo *int32 `protobuf:"varint,3,opt,name=port_to,json=portTo,proto3,oneof" json:"port_to,omitempty"`
	// IPv4 CIDR block for source (ingress) or destination (egress) addresses.
	//
	// Must be valid CIDR notation. Use '0.0.0.0/0' to match all IPv4 addresses. Validation enforced at
	// service layer.
	//
	// Example: '192.168.1.0/24', '10.0.0.0/8', '0.0.0.0/0' (all IPv4)
	Ipv4Cidr *string `protobuf:"bytes,4,opt,name=ipv4_cidr,json=ipv4Cidr,proto3,oneof" json:"ipv4_cidr,omitempty"`
	// IPv6 CIDR block for source (ingress) or destination (egress) addresses.
	//
	// Must be valid CIDR notation. Use '::/0' to match all IPv6 addresses. Validation enforced at service
	// layer.
	//
	// Example: '2001:db8::/32', 'fd00::/64', '::/0' (all IPv6)
	Ipv6Cidr      *string `protobuf:"bytes,5,opt,name=ipv6_cidr,json=ipv6Cidr,proto3,oneof" json:"ipv6_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRule) Reset() {
	*x = SecurityRule{}
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRule) ProtoMessage() {}

func (x *SecurityRule) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityRule) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *SecurityRule) GetPortFrom() int32 {
	if x != nil && x.PortFrom != nil {
		return *x.PortFrom
	}
	return 0
}

func (x *SecurityRule) GetPortTo() int32 {
	if x != nil && x.PortTo != nil {
		return *x.PortTo
	}
	return 0
}

func (x *SecurityRule) GetIpv4Cidr() string {
	if x != nil && x.Ipv4Cidr != nil {
		return *x.Ipv4Cidr
	}
	return ""
}

func (x *SecurityRule) GetIpv6Cidr() string {
	if x != nil && x.Ipv6Cidr != nil {
		return *x.Ipv6Cidr
	}
	return ""
}

func (x *SecurityRule) SetProtocol(v Protocol) {
	x.Protocol = v
}

func (x *SecurityRule) SetPortFrom(v int32) {
	x.PortFrom = &v
}

func (x *SecurityRule) SetPortTo(v int32) {
	x.PortTo = &v
}

func (x *SecurityRule) SetIpv4Cidr(v string) {
	x.Ipv4Cidr = &v
}

func (x *SecurityRule) SetIpv6Cidr(v string) {
	x.Ipv6Cidr = &v
}

func (x *SecurityRule) HasPortFrom() bool {
	if x == nil {
		return false
	}
	return x.PortFrom != nil
}

func (x *SecurityRule) HasPortTo() bool {
	if x == nil {
		return false
	}
	return x.PortTo != nil
}

func (x *SecurityRule) HasIpv4Cidr() bool {
	if x == nil {
		return false
	}
	return x.Ipv4Cidr != nil
}

func (x *SecurityRule) HasIpv6Cidr() bool {
	if x == nil {
		return false
	}
	return x.Ipv6Cidr != nil
}

func (x *SecurityRule) ClearPortFrom() {
	x.PortFrom = nil
}

func (x *SecurityRule) ClearPortTo() {
	x.PortTo = nil
}

func (x *SecurityRule) ClearIpv4Cidr() {
	x.Ipv4Cidr = nil
}

func (x *SecurityRule) ClearIpv6Cidr() {
	x.Ipv6Cidr = nil
}

type SecurityRule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Protocol to match for this rule.
	//
	// Use PROTOCOL_ALL to match all protocols (wildcard). Use PROTOCOL_TCP or PROTOCOL_UDP when port ranges
	// are needed. Use PROTOCOL_ICMP for ping and other ICMP traffic.
	Protocol Protocol
	// Starting port number for the rule (1-65535).
	//
	// Required for tcp/udp protocols, ignored for icmp/all. For single port, set port_from = port_to.
	// Must be <= port_to. Validation enforced at service layer.
	//
	// Example: 22 (SSH), 80 (HTTP), 443 (HTTPS), 3306 (MySQL)
	PortFrom *int32
	// Ending port number for the rule (1-65535).
	//
	// Required for tcp/udp protocols, ignored for icmp/all. Must be >= port_from. For single port, set
	// port_from = port_to. Validation enforced at service layer.
	//
	// Example: 22 (single port), 8000 (range 8000-9000)
	PortTo *int32
	// IPv4 CIDR block for source (ingress) or destination (egress) addresses.
	//
	// Must be valid CIDR notation. Use '0.0.0.0/0' to match all IPv4 addresses. Validation enforced at
	// service layer.
	//
	// Example: '192.168.1.0/24', '10.0.0.0/8', '0.0.0.0/0' (all IPv4)
	Ipv4Cidr *string
	// IPv6 CIDR block for source (ingress) or destination (egress) addresses.
	//
	// Must be valid CIDR notation. Use '::/0' to match all IPv6 addresses. Validation enforced at service
	// layer.
	//
	// Example: '2001:db8::/32', 'fd00::/64', '::/0' (all IPv6)
	Ipv6Cidr *string
}

func (b0 SecurityRule_builder) Build() *SecurityRule {
	m0 := &SecurityRule{}
	b, x := &b0, m0
	_, _ = b, x
	x.Protocol = b.Protocol
	x.PortFrom = b.PortFrom
	x.PortTo = b.PortTo
	x.Ipv4Cidr = b.Ipv4Cidr
	x.Ipv6Cidr = b.Ipv6Cidr
	return m0
}

// Represents the current operational state of a SecurityGroup.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the system updates
// them based on the reconciliation of the spec and the state of the parent VirtualNetwork.
type SecurityGroupStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the security group.
	State SecurityGroupState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.SecurityGroupState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, this might contain progress information like "Validating rules" or "Configuring
	// firewall backend".
	//
	// For FAILED state, this contains error details explaining what went wrong, such as:
	// - "Invalid port range: port_from (100) > port_to (50)"
	// - "Parent VirtualNetwork not found: vnet-12345"
	// - "Parent VirtualNetwork not in READY state"
	// - "Invalid IPv4 CIDR: 192.168.1.0/33"
	// - "Protocol tcp requires port_from and port_to fields"
	//
	// For READY state, this is typically empty or contains confirmation like "Security group active, rules
	// enforced".
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityGroupStatus) Reset() {
	*x = SecurityGroupStatus{}
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityGroupStatus) ProtoMessage() {}

func (x *SecurityGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_security_group_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityGroupStatus) GetState() SecurityGroupState {
	if x != nil {
		return x.State
	}
	return SecurityGroupState_SECURITY_GROUP_STATE_UNSPECIFIED
}

func (x *SecurityGroupStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *SecurityGroupStatus) SetState(v SecurityGroupState) {
	x.State = v
}

func (x *SecurityGroupStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *SecurityGroupStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *SecurityGroupStatus) ClearMessage() {
	x.Message = nil
}

type SecurityGroupStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the security group.
	State SecurityGroupState
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, this might contain progress information like "Validating rules" or "Configuring
	// firewall backend".
	//
	// For FAILED state, this contains error details explaining what went wrong, such as:
	// - "Invalid port range: port_from (100) > port_to (50)"
	// - "Parent VirtualNetwork not found: vnet-12345"
	// - "Parent VirtualNetwork not in READY state"
	// - "Invalid IPv4 CIDR: 192.168.1.0/33"
	// - "Protocol tcp requires port_from and port_to fields"
	//
	// For READY state, this is typically empty or contains confirmation like "Security group active, rules
	// enforced".
	Message *string
}

func (b0 SecurityGroupStatus_builder) Build() *SecurityGroupStatus {
	m0 := &SecurityGroupStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	return m0
}

var File_osac_private_v1_security_group_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_security_group_type_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f,
	0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xb4, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x2f, 0x0a, 0x0f, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x06, 0xe0, 0x41, 0x02, 0xe0, 0x41, 0x05, 0x52, 0x0e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x37, 0x0a, 0x07, 0x69, 0x6e, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x35, 0x0a, 0x06, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x06, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0xff, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x20, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x88,
	0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x09, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x69, 0x70, 0x76, 0x34, 0x43, 0x69, 0x64, 0x72, 0x88,
	0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x08, 0x69, 0x70, 0x76, 0x36, 0x43, 0x69, 0x64,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x66, 0x72,
	0x6f, 0x6d, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x6f, 0x42, 0x0c,
	0x0a, 0x0a, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x22, 0x7b, 0x0a, 0x13, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x6d, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x54, 0x43, 0x50, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x55, 0x44, 0x50, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x49, 0x43,
	0x4d, 0x50, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c,
	0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x04, 0x2a, 0xe8, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a,
	0x20, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x5f,
	0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54,
	0x59, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54,
	0x59, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49,
	0x54, 0x59, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44,
	0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x26, 0x0a, 0x22, 0x53, 0x45, 0x43,
	0x55, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x05, 0x42, 0xdb, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x16, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f,
	0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73,
	0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_security_group_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_osac_private_v1_security_group_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_security_group_type_proto_goTypes = []any{
	(Protocol)(0),               // 0: osac.private.v1.Protocol
	(SecurityGroupState)(0),     // 1: osac.private.v1.SecurityGroupState
	(*SecurityGroup)(nil),       // 2: osac.private.v1.SecurityGroup
	(*SecurityGroupSpec)(nil),   // 3: osac.private.v1.SecurityGroupSpec
	(*SecurityRule)(nil),        // 4: osac.private.v1.SecurityRule
	(*SecurityGroupStatus)(nil), // 5: osac.private.v1.SecurityGroupStatus
	(*Metadata)(nil),            // 6: osac.private.v1.Metadata
}
var file_osac_private_v1_security_group_type_proto_depIdxs = []int32{
	6, // 0: osac.private.v1.SecurityGroup.metadata:type_name -> osac.private.v1.Metadata
	3, // 1: osac.private.v1.SecurityGroup.spec:type_name -> osac.private.v1.SecurityGroupSpec
	5, // 2: osac.private.v1.SecurityGroup.status:type_name -> osac.private.v1.SecurityGroupStatus
	4, // 3: osac.private.v1.SecurityGroupSpec.ingress:type_name -> osac.private.v1.SecurityRule
	4, // 4: osac.private.v1.SecurityGroupSpec.egress:type_name -> osac.private.v1.SecurityRule
	0, // 5: osac.private.v1.SecurityRule.protocol:type_name -> osac.private.v1.Protocol
	1, // 6: osac.private.v1.SecurityGroupStatus.state:type_name -> osac.private.v1.SecurityGroupState
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_osac_private_v1_security_group_type_proto_init() }
func file_osac_private_v1_security_group_type_proto_init() {
	if File_osac_private_v1_security_group_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_security_group_type_proto_msgTypes[2].OneofWrappers = []any{}
	file_osac_private_v1_security_group_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_security_group_type_proto_rawDesc), len(file_osac_private_v1_security_group_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_security_group_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_security_group_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_security_group_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_security_group_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_security_group_type_proto = out.File
	file_osac_private_v1_security_group_type_proto_goTypes = nil
	file_osac_private_v1_security_group_type_proto_depIdxs = nil
}
