//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/subnet_type.proto

//go:build protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for Subnet resources.
//
// State transitions typically follow: UNSPECIFIED -> PENDING -> READY, with FAILED as a terminal error state
// that may require user intervention or resource recreation.
type SubnetState int32

const (
	// State is unknown or has not been determined yet. This is the default state before initialization.
	SubnetState_SUBNET_STATE_UNSPECIFIED SubnetState = 0
	// The subnet is being initialized and is not ready for use yet.
	//
	// During this state, the system is:
	// - Validating that the parent VirtualNetwork exists and is in READY state
	// - Validating CIDR blocks (format, subset of parent, no overlaps)
	// - Allocating IP address space within the parent VirtualNetwork
	// - Configuring subnet routing and network policies
	//
	// Compute instances cannot be attached to subnets in PENDING state.
	SubnetState_SUBNET_STATE_PENDING SubnetState = 1
	// The subnet is fully operational and ready for compute instances to attach.
	//
	// In this state:
	// - CIDR blocks are allocated and validated
	// - Parent VirtualNetwork is in READY state
	// - Subnet routing is configured
	// - Compute instances can be created and attached
	// - IP address allocation is active
	SubnetState_SUBNET_STATE_READY SubnetState = 2
	// The subnet has encountered an error and is unusable.
	//
	// Common failure reasons include:
	// - Invalid CIDR notation
	// - CIDR block is not a subset of parent VirtualNetwork CIDR
	// - CIDR block overlaps with existing subnets in the same VirtualNetwork
	// - Parent VirtualNetwork not found
	// - Parent VirtualNetwork not in READY state
	// - Network configuration error
	//
	// The status.message field will contain specific error details. Failed subnets typically require deletion
	// and recreation with corrected parameters.
	SubnetState_SUBNET_STATE_FAILED SubnetState = 3
	// The subnet is being deleted.
	//
	// During this state, the system is:
	// - Removing network policies and routing rules
	// - Deallocating IP address space
	// - Cleaning up backend network resources
	//
	// The subnet will be archived once deletion completes successfully.
	SubnetState_SUBNET_STATE_DELETING SubnetState = 4
	// The subnet deletion has failed.
	//
	// The deprovision operation encountered an error and could not complete.
	// The status.message field will contain specific error details.
	// Manual intervention may be required to resolve the underlying issue
	// before retrying deletion.
	SubnetState_SUBNET_STATE_DELETE_FAILED SubnetState = 5
)

// Enum value maps for SubnetState.
var (
	SubnetState_name = map[int32]string{
		0: "SUBNET_STATE_UNSPECIFIED",
		1: "SUBNET_STATE_PENDING",
		2: "SUBNET_STATE_READY",
		3: "SUBNET_STATE_FAILED",
		4: "SUBNET_STATE_DELETING",
		5: "SUBNET_STATE_DELETE_FAILED",
	}
	SubnetState_value = map[string]int32{
		"SUBNET_STATE_UNSPECIFIED":   0,
		"SUBNET_STATE_PENDING":       1,
		"SUBNET_STATE_READY":         2,
		"SUBNET_STATE_FAILED":        3,
		"SUBNET_STATE_DELETING":      4,
		"SUBNET_STATE_DELETE_FAILED": 5,
	}
)

func (x SubnetState) Enum() *SubnetState {
	p := new(SubnetState)
	*p = x
	return p
}

func (x SubnetState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubnetState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_subnet_type_proto_enumTypes[0].Descriptor()
}

func (SubnetState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_subnet_type_proto_enumTypes[0]
}

func (x SubnetState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a subdivision of a VirtualNetwork for organizing compute instances.
//
// Subnets subdivide VirtualNetwork IP address space into smaller, manageable segments. Each Subnet belongs to exactly
// one parent VirtualNetwork and must be in the same region. Initially, the system supports a 1:1 mapping between
// VirtualNetwork and Subnet (one subnet per network), but the schema is designed to support multiple subnets per
// VirtualNetwork in the future.
//
// Subnets support flexible IP addressing to match the parent VirtualNetwork's capabilities:
// - IPv4-only: Set ipv4_cidr, leave ipv6_cidr empty
// - IPv6-only: Set ipv6_cidr, leave ipv4_cidr empty
// - Dual-stack: Set both ipv4_cidr and ipv6_cidr
//
// The parent VirtualNetwork relationship should be specified via metadata.annotations using the 'osac.openshift.io/owner-reference'
// key with the VirtualNetwork ID as the value. This establishes resource hierarchy for garbage collection, ensuring
// that Subnets are automatically cleaned up when their parent VirtualNetwork is deleted.
//
// CIDR blocks must be non-overlapping within the same VirtualNetwork. Each Subnet's CIDR must be a subset of the
// parent VirtualNetwork's CIDR. Validation is enforced at the service layer.
type Subnet struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *SubnetSpec            `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *SubnetStatus          `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_osac_private_v1_subnet_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_subnet_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Subnet) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Subnet) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Subnet) GetSpec() *SubnetSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *Subnet) GetStatus() *SubnetStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Subnet) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Subnet) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Subnet) SetSpec(v *SubnetSpec) {
	x.xxx_hidden_Spec = v
}

func (x *Subnet) SetStatus(v *SubnetStatus) {
	x.xxx_hidden_Status = v
}

func (x *Subnet) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Subnet) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *Subnet) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Subnet) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Subnet) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *Subnet) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type Subnet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the subnet.
	Id string
	// Metadata of the subnet, including name, labels, tenant, and timestamps.
	//
	// The parent VirtualNetwork relationship should be specified via metadata.annotations using the
	// 'osac.openshift.io/owner-reference' key with the VirtualNetwork ID as the value. This establishes resource
	// hierarchy for garbage collection.
	Metadata *Metadata
	// Desired configuration of the subnet (user-modifiable).
	Spec *SubnetSpec
	// Current state of the subnet (system-provided, read-only).
	Status *SubnetStatus
}

func (b0 Subnet_builder) Build() *Subnet {
	m0 := &Subnet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// Defines the desired configuration for a Subnet.
//
// The spec contains user-specified parameters that define how the subnet should be configured. These fields
// follow a declarative model where users specify the desired state and the system reconciles to match it.
type SubnetSpec struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VirtualNetwork string                 `protobuf:"bytes,1,opt,name=virtual_network,json=virtualNetwork,proto3"`
	xxx_hidden_Ipv4Cidr       *string                `protobuf:"bytes,2,opt,name=ipv4_cidr,json=ipv4Cidr,proto3,oneof"`
	xxx_hidden_Ipv6Cidr       *string                `protobuf:"bytes,3,opt,name=ipv6_cidr,json=ipv6Cidr,proto3,oneof"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SubnetSpec) Reset() {
	*x = SubnetSpec{}
	mi := &file_osac_private_v1_subnet_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetSpec) ProtoMessage() {}

func (x *SubnetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_subnet_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubnetSpec) GetVirtualNetwork() string {
	if x != nil {
		return x.xxx_hidden_VirtualNetwork
	}
	return ""
}

func (x *SubnetSpec) GetIpv4Cidr() string {
	if x != nil {
		if x.xxx_hidden_Ipv4Cidr != nil {
			return *x.xxx_hidden_Ipv4Cidr
		}
		return ""
	}
	return ""
}

func (x *SubnetSpec) GetIpv6Cidr() string {
	if x != nil {
		if x.xxx_hidden_Ipv6Cidr != nil {
			return *x.xxx_hidden_Ipv6Cidr
		}
		return ""
	}
	return ""
}

func (x *SubnetSpec) SetVirtualNetwork(v string) {
	x.xxx_hidden_VirtualNetwork = v
}

func (x *SubnetSpec) SetIpv4Cidr(v string) {
	x.xxx_hidden_Ipv4Cidr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SubnetSpec) SetIpv6Cidr(v string) {
	x.xxx_hidden_Ipv6Cidr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SubnetSpec) HasIpv4Cidr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SubnetSpec) HasIpv6Cidr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SubnetSpec) ClearIpv4Cidr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ipv4Cidr = nil
}

func (x *SubnetSpec) ClearIpv6Cidr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Ipv6Cidr = nil
}

type SubnetSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Parent VirtualNetwork ID. Required and immutable after creation.
	//
	// Must reference the ID of an existing VirtualNetwork in READY state. This field is required and immutable
	// after creation. The referenced VirtualNetwork must be in the same region as this Subnet.
	//
	// The system validates that:
	// - The VirtualNetwork exists
	// - The VirtualNetwork.status.state is READY
	// - The Subnet's CIDR blocks are subsets of the VirtualNetwork's CIDR blocks
	// - The Subnet's CIDR blocks do not overlap with other Subnets in the same VirtualNetwork
	//
	// Example: "vnet-abc123"
	VirtualNetwork string
	// IPv4 CIDR block for this subnet. Optional for IPv6-only subnets. Immutable after creation.
	//
	// Must be valid CIDR notation and a subset of the parent VirtualNetwork.spec.ipv4_cidr. Validation enforced
	// at service layer. The CIDR block must not overlap with other Subnets within the same VirtualNetwork.
	//
	// Example: "10.0.1.0/24", "192.168.100.0/24"
	//
	// Leave empty for IPv6-only subnets.
	Ipv4Cidr *string
	// IPv6 CIDR block for this subnet. Optional for IPv4-only subnets. Immutable after creation.
	//
	// Must be valid CIDR notation and a subset of the parent VirtualNetwork.spec.ipv6_cidr. Validation enforced
	// at service layer. The CIDR block must not overlap with other Subnets within the same VirtualNetwork.
	//
	// Example: "2001:db8::/64", "fd00:1234::/64"
	//
	// Leave empty for IPv4-only subnets.
	Ipv6Cidr *string
}

func (b0 SubnetSpec_builder) Build() *SubnetSpec {
	m0 := &SubnetSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_VirtualNetwork = b.VirtualNetwork
	if b.Ipv4Cidr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Ipv4Cidr = b.Ipv4Cidr
	}
	if b.Ipv6Cidr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Ipv6Cidr = b.Ipv6Cidr
	}
	return m0
}

// Represents the current operational state of a Subnet.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the system updates them
// based on the reconciliation of the spec.
type SubnetStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       SubnetState            `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.SubnetState"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	xxx_hidden_Hub         string                 `protobuf:"bytes,3,opt,name=hub,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubnetStatus) Reset() {
	*x = SubnetStatus{}
	mi := &file_osac_private_v1_subnet_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetStatus) ProtoMessage() {}

func (x *SubnetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_subnet_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubnetStatus) GetState() SubnetState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return SubnetState_SUBNET_STATE_UNSPECIFIED
}

func (x *SubnetStatus) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *SubnetStatus) GetHub() string {
	if x != nil {
		return x.xxx_hidden_Hub
	}
	return ""
}

func (x *SubnetStatus) SetState(v SubnetState) {
	x.xxx_hidden_State = v
}

func (x *SubnetStatus) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SubnetStatus) SetHub(v string) {
	x.xxx_hidden_Hub = v
}

func (x *SubnetStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SubnetStatus) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type SubnetStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the subnet.
	State SubnetState
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, this might contain progress information like "Validating CIDR blocks" or
	// "Configuring subnet routing".
	//
	// For FAILED state, contains error details like:
	// - "CIDR overlaps with existing subnet"
	// - "Parent VirtualNetwork not found"
	// - "CIDR is not a subset of parent VirtualNetwork CIDR"
	// - "Invalid CIDR notation"
	// - "Parent VirtualNetwork not in READY state"
	//
	// For READY state, this is typically empty or contains confirmation like "Subnet ready for compute instances".
	Message *string
	// Identifier of the hub that was selected for this subnet.
	//
	// The fulfillment-service controller randomly selects a hub from available hubs and stores the hub ID here.
	// This tracks which hub cluster the Subnet CR is deployed to for reconciliation and cleanup.
	Hub string
}

func (b0 SubnetStatus_builder) Build() *SubnetStatus {
	m0 := &SubnetStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_Hub = b.Hub
	return m0
}

var File_osac_private_v1_subnet_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_subnet_type_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x06, 0x53,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x2f, 0x0a, 0x0f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe0, 0x41,
	0x02, 0xe0, 0x41, 0x05, 0x52, 0x0e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x25, 0x0a, 0x09, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x63, 0x69, 0x64,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x05, 0x48, 0x00, 0x52, 0x08,
	0x69, 0x70, 0x76, 0x34, 0x43, 0x69, 0x64, 0x72, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x09, 0x69,
	0x70, 0x76, 0x36, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03,
	0xe0, 0x41, 0x05, 0x48, 0x01, 0x52, 0x08, 0x69, 0x70, 0x76, 0x36, 0x43, 0x69, 0x64, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x63, 0x69, 0x64, 0x72,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x22, 0x7f,
	0x0a, 0x0c, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x68, 0x75, 0x62, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0xb1, 0x01, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1c, 0x0a, 0x18, 0x53, 0x55, 0x42, 0x4e, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x53, 0x55, 0x42, 0x4e, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x55, 0x42, 0x4e, 0x45,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12,
	0x17, 0x0a, 0x13, 0x53, 0x55, 0x42, 0x4e, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x55, 0x42, 0x4e,
	0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x04, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x55, 0x42, 0x4e, 0x45, 0x54, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x05, 0x42, 0xd4, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x53, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f,
	0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var file_osac_private_v1_subnet_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_subnet_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_subnet_type_proto_goTypes = []any{
	(SubnetState)(0),     // 0: osac.private.v1.SubnetState
	(*Subnet)(nil),       // 1: osac.private.v1.Subnet
	(*SubnetSpec)(nil),   // 2: osac.private.v1.SubnetSpec
	(*SubnetStatus)(nil), // 3: osac.private.v1.SubnetStatus
	(*Metadata)(nil),     // 4: osac.private.v1.Metadata
}
var file_osac_private_v1_subnet_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.Subnet.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.Subnet.spec:type_name -> osac.private.v1.SubnetSpec
	3, // 2: osac.private.v1.Subnet.status:type_name -> osac.private.v1.SubnetStatus
	0, // 3: osac.private.v1.SubnetStatus.state:type_name -> osac.private.v1.SubnetState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_subnet_type_proto_init() }
func file_osac_private_v1_subnet_type_proto_init() {
	if File_osac_private_v1_subnet_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_subnet_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_osac_private_v1_subnet_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_subnet_type_proto_rawDesc), len(file_osac_private_v1_subnet_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_subnet_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_subnet_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_subnet_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_subnet_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_subnet_type_proto = out.File
	file_osac_private_v1_subnet_type_proto_goTypes = nil
	file_osac_private_v1_subnet_type_proto_depIdxs = nil
}
