//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/virtual_network_type.proto

//go:build protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for VirtualNetwork resources.
//
// State transitions typically follow: UNSPECIFIED -> PENDING -> READY, with FAILED as a terminal error state
// that may require user intervention or resource recreation.
type VirtualNetworkState int32

const (
	// State is unknown or has not been determined yet. This is the default state before initialization.
	VirtualNetworkState_VIRTUAL_NETWORK_STATE_UNSPECIFIED VirtualNetworkState = 0
	// The virtual network is being initialized and is not ready for use yet.
	//
	// During this state, the system is:
	// - Validating CIDR blocks
	// - Checking NetworkClass compatibility
	// - Allocating IP address space
	// - Configuring the network backend
	//
	// Compute instances cannot be attached to networks in PENDING state.
	VirtualNetworkState_VIRTUAL_NETWORK_STATE_PENDING VirtualNetworkState = 1
	// The virtual network is fully operational and ready for compute instances to attach.
	//
	// In this state:
	// - CIDR blocks are allocated and configured
	// - Network backend is ready
	// - Compute instances can be created and attached
	// - Network isolation and routing are active
	VirtualNetworkState_VIRTUAL_NETWORK_STATE_READY VirtualNetworkState = 2
	// The virtual network has encountered an error and is unusable.
	//
	// Common failure reasons include:
	// - Invalid CIDR notation
	// - CIDR block conflicts with existing networks
	// - NetworkClass does not support requested capabilities (e.g., dual-stack not supported)
	// - NetworkClass is not in READY state
	// - Network backend configuration error
	//
	// The status.message field will contain specific error details. Failed networks typically require deletion
	// and recreation with corrected parameters.
	VirtualNetworkState_VIRTUAL_NETWORK_STATE_FAILED VirtualNetworkState = 3
)

// Enum value maps for VirtualNetworkState.
var (
	VirtualNetworkState_name = map[int32]string{
		0: "VIRTUAL_NETWORK_STATE_UNSPECIFIED",
		1: "VIRTUAL_NETWORK_STATE_PENDING",
		2: "VIRTUAL_NETWORK_STATE_READY",
		3: "VIRTUAL_NETWORK_STATE_FAILED",
	}
	VirtualNetworkState_value = map[string]int32{
		"VIRTUAL_NETWORK_STATE_UNSPECIFIED": 0,
		"VIRTUAL_NETWORK_STATE_PENDING":     1,
		"VIRTUAL_NETWORK_STATE_READY":       2,
		"VIRTUAL_NETWORK_STATE_FAILED":      3,
	}
)

func (x VirtualNetworkState) Enum() *VirtualNetworkState {
	p := new(VirtualNetworkState)
	*p = x
	return p
}

func (x VirtualNetworkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualNetworkState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_virtual_network_type_proto_enumTypes[0].Descriptor()
}

func (VirtualNetworkState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_virtual_network_type_proto_enumTypes[0]
}

func (x VirtualNetworkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a tenant-isolated virtual network.
//
// VirtualNetwork provides network isolation for compute instances within a region. Each VirtualNetwork is backed
// by a specific NetworkClass implementation strategy (e.g., "udn-net" for User-Defined Networks, "phys-net" for
// physical network infrastructure).
//
// VirtualNetworks support flexible IP addressing:
// - IPv4-only: Set ipv4_cidr, leave ipv6_cidr empty
// - IPv6-only: Set ipv6_cidr, leave ipv4_cidr empty
// - Dual-stack: Set both ipv4_cidr and ipv6_cidr
//
// The selected NetworkClass must support the requested IP addressing mode via its capabilities.
//
// Tenant isolation is enforced via the standard Metadata tenants field. VirtualNetworks are scoped to
// a single region and cannot span multiple regions.
type VirtualNetwork struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *VirtualNetworkSpec    `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *VirtualNetworkStatus  `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VirtualNetwork) Reset() {
	*x = VirtualNetwork{}
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualNetwork) ProtoMessage() {}

func (x *VirtualNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VirtualNetwork) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *VirtualNetwork) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *VirtualNetwork) GetSpec() *VirtualNetworkSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *VirtualNetwork) GetStatus() *VirtualNetworkStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *VirtualNetwork) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *VirtualNetwork) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *VirtualNetwork) SetSpec(v *VirtualNetworkSpec) {
	x.xxx_hidden_Spec = v
}

func (x *VirtualNetwork) SetStatus(v *VirtualNetworkStatus) {
	x.xxx_hidden_Status = v
}

func (x *VirtualNetwork) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *VirtualNetwork) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *VirtualNetwork) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *VirtualNetwork) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *VirtualNetwork) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *VirtualNetwork) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type VirtualNetwork_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the virtual network.
	Id string
	// Metadata of the virtual network, including name, labels, tenants, and timestamps.
	Metadata *Metadata
	// Desired configuration of the virtual network (user-modifiable).
	Spec *VirtualNetworkSpec
	// Current state of the virtual network (system-provided, read-only).
	Status *VirtualNetworkStatus
}

func (b0 VirtualNetwork_builder) Build() *VirtualNetwork {
	m0 := &VirtualNetwork{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// Defines the desired configuration for a VirtualNetwork.
//
// The spec contains user-specified parameters that define how the network should be configured. These fields
// follow a declarative model where users specify the desired state and the system reconciles to match it.
type VirtualNetworkSpec struct {
	state                             protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Region                 string                      `protobuf:"bytes,1,opt,name=region,proto3"`
	xxx_hidden_NetworkClass           string                      `protobuf:"bytes,2,opt,name=network_class,json=networkClass,proto3"`
	xxx_hidden_Ipv4Cidr               *string                     `protobuf:"bytes,3,opt,name=ipv4_cidr,json=ipv4Cidr,proto3,oneof"`
	xxx_hidden_Ipv6Cidr               *string                     `protobuf:"bytes,4,opt,name=ipv6_cidr,json=ipv6Cidr,proto3,oneof"`
	xxx_hidden_Capabilities           *VirtualNetworkCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3"`
	xxx_hidden_ImplementationStrategy string                      `protobuf:"bytes,6,opt,name=implementation_strategy,json=implementationStrategy,proto3"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *VirtualNetworkSpec) Reset() {
	*x = VirtualNetworkSpec{}
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualNetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualNetworkSpec) ProtoMessage() {}

func (x *VirtualNetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VirtualNetworkSpec) GetRegion() string {
	if x != nil {
		return x.xxx_hidden_Region
	}
	return ""
}

func (x *VirtualNetworkSpec) GetNetworkClass() string {
	if x != nil {
		return x.xxx_hidden_NetworkClass
	}
	return ""
}

func (x *VirtualNetworkSpec) GetIpv4Cidr() string {
	if x != nil {
		if x.xxx_hidden_Ipv4Cidr != nil {
			return *x.xxx_hidden_Ipv4Cidr
		}
		return ""
	}
	return ""
}

func (x *VirtualNetworkSpec) GetIpv6Cidr() string {
	if x != nil {
		if x.xxx_hidden_Ipv6Cidr != nil {
			return *x.xxx_hidden_Ipv6Cidr
		}
		return ""
	}
	return ""
}

func (x *VirtualNetworkSpec) GetCapabilities() *VirtualNetworkCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *VirtualNetworkSpec) GetImplementationStrategy() string {
	if x != nil {
		return x.xxx_hidden_ImplementationStrategy
	}
	return ""
}

func (x *VirtualNetworkSpec) SetRegion(v string) {
	x.xxx_hidden_Region = v
}

func (x *VirtualNetworkSpec) SetNetworkClass(v string) {
	x.xxx_hidden_NetworkClass = v
}

func (x *VirtualNetworkSpec) SetIpv4Cidr(v string) {
	x.xxx_hidden_Ipv4Cidr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *VirtualNetworkSpec) SetIpv6Cidr(v string) {
	x.xxx_hidden_Ipv6Cidr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *VirtualNetworkSpec) SetCapabilities(v *VirtualNetworkCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *VirtualNetworkSpec) SetImplementationStrategy(v string) {
	x.xxx_hidden_ImplementationStrategy = v
}

func (x *VirtualNetworkSpec) HasIpv4Cidr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VirtualNetworkSpec) HasIpv6Cidr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VirtualNetworkSpec) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *VirtualNetworkSpec) ClearIpv4Cidr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Ipv4Cidr = nil
}

func (x *VirtualNetworkSpec) ClearIpv6Cidr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Ipv6Cidr = nil
}

func (x *VirtualNetworkSpec) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

type VirtualNetworkSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Region where the network is created. This is required and immutable after creation.
	//
	// VirtualNetworks are region-scoped resources and cannot span multiple regions. Compute instances can only
	// attach to VirtualNetworks in the same region.
	//
	// Example: "us-east-1", "eu-west-2"
	Region string
	// The NetworkClass for this VirtualNetwork. If omitted on creation, the default NetworkClass is used.
	// Once set (either explicitly or via default), this field is immutable.
	//
	// This field stores the ID of the selected NetworkClass resource. The selected NetworkClass determines the
	// network backend (implementation_strategy) and the available capabilities.
	//
	// The NetworkClass must support the requested IP addressing capabilities (IPv4, IPv6, or dual-stack) specified
	// via the capabilities field.
	//
	// Example: "udn-net", "phys-net", "ovn-kubernetes"
	NetworkClass string
	// IPv4 CIDR block for this network. Optional for IPv6-only networks. Immutable after creation.
	//
	// Must be valid CIDR notation. Validation enforced at service layer.
	// The CIDR block should be appropriately sized for the expected number of compute instances.
	//
	// Example: "10.0.0.0/16", "192.168.0.0/24"
	//
	// Leave empty when creating an IPv6-only network.
	Ipv4Cidr *string
	// IPv6 CIDR block for this network. Optional for IPv4-only networks. Immutable after creation.
	//
	// Must be valid CIDR notation. Validation enforced at service layer.
	// IPv6 addresses should follow standard allocation practices for tenant networks.
	//
	// Example: "2001:db8::/48", "fd00::/64"
	//
	// Leave empty when creating an IPv4-only network.
	Ipv6Cidr *string
	// Requested network capabilities for this VirtualNetwork.
	//
	// These capabilities must be compatible with the selected NetworkClass.capabilities. The system will validate
	// that the NetworkClass supports the requested addressing mode before creating the network.
	Capabilities *VirtualNetworkCapabilities
	// Implementation strategy for provisioning this network.
	//
	// This determines the underlying network backend and Ansible role to use (e.g., "cudn" uses cudn_virtual_network
	// role). The value is derived from the NetworkClass at creation time and stored here for direct access by
	// controllers and provisioning systems.
	//
	// This field is set by the system based on the selected network_class and is immutable after creation.
	//
	// Example: "cudn", "physnet", "ovn"
	ImplementationStrategy string
}

func (b0 VirtualNetworkSpec_builder) Build() *VirtualNetworkSpec {
	m0 := &VirtualNetworkSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Region = b.Region
	x.xxx_hidden_NetworkClass = b.NetworkClass
	if b.Ipv4Cidr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Ipv4Cidr = b.Ipv4Cidr
	}
	if b.Ipv6Cidr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Ipv6Cidr = b.Ipv6Cidr
	}
	x.xxx_hidden_Capabilities = b.Capabilities
	x.xxx_hidden_ImplementationStrategy = b.ImplementationStrategy
	return m0
}

// Describes the IP addressing capabilities requested for a VirtualNetwork.
//
// These flags must be compatible with the selected NetworkClass.capabilities. For example, if enable_dual_stack
// is true, the selected NetworkClass must have supports_dual_stack set to true.
type VirtualNetworkCapabilities struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EnableIpv4      bool                   `protobuf:"varint,1,opt,name=enable_ipv4,json=enableIpv4,proto3"`
	xxx_hidden_EnableIpv6      bool                   `protobuf:"varint,2,opt,name=enable_ipv6,json=enableIpv6,proto3"`
	xxx_hidden_EnableDualStack bool                   `protobuf:"varint,3,opt,name=enable_dual_stack,json=enableDualStack,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VirtualNetworkCapabilities) Reset() {
	*x = VirtualNetworkCapabilities{}
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualNetworkCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualNetworkCapabilities) ProtoMessage() {}

func (x *VirtualNetworkCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VirtualNetworkCapabilities) GetEnableIpv4() bool {
	if x != nil {
		return x.xxx_hidden_EnableIpv4
	}
	return false
}

func (x *VirtualNetworkCapabilities) GetEnableIpv6() bool {
	if x != nil {
		return x.xxx_hidden_EnableIpv6
	}
	return false
}

func (x *VirtualNetworkCapabilities) GetEnableDualStack() bool {
	if x != nil {
		return x.xxx_hidden_EnableDualStack
	}
	return false
}

func (x *VirtualNetworkCapabilities) SetEnableIpv4(v bool) {
	x.xxx_hidden_EnableIpv4 = v
}

func (x *VirtualNetworkCapabilities) SetEnableIpv6(v bool) {
	x.xxx_hidden_EnableIpv6 = v
}

func (x *VirtualNetworkCapabilities) SetEnableDualStack(v bool) {
	x.xxx_hidden_EnableDualStack = v
}

type VirtualNetworkCapabilities_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether IPv4 is enabled for this network. Should be true when ipv4_cidr is set.
	EnableIpv4 bool
	// Whether IPv6 is enabled for this network. Should be true when ipv6_cidr is set.
	EnableIpv6 bool
	// Whether dual-stack mode (both IPv4 and IPv6) is enabled. Should be true when both ipv4_cidr and ipv6_cidr
	// are set.
	EnableDualStack bool
}

func (b0 VirtualNetworkCapabilities_builder) Build() *VirtualNetworkCapabilities {
	m0 := &VirtualNetworkCapabilities{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EnableIpv4 = b.EnableIpv4
	x.xxx_hidden_EnableIpv6 = b.EnableIpv6
	x.xxx_hidden_EnableDualStack = b.EnableDualStack
	return m0
}

// Represents the current operational state of a VirtualNetwork.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the system updates them
// based on the reconciliation of the spec.
type VirtualNetworkStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       VirtualNetworkState    `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.VirtualNetworkState"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	xxx_hidden_Hub         string                 `protobuf:"bytes,3,opt,name=hub,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VirtualNetworkStatus) Reset() {
	*x = VirtualNetworkStatus{}
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualNetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualNetworkStatus) ProtoMessage() {}

func (x *VirtualNetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_virtual_network_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VirtualNetworkStatus) GetState() VirtualNetworkState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return VirtualNetworkState_VIRTUAL_NETWORK_STATE_UNSPECIFIED
}

func (x *VirtualNetworkStatus) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *VirtualNetworkStatus) GetHub() string {
	if x != nil {
		return x.xxx_hidden_Hub
	}
	return ""
}

func (x *VirtualNetworkStatus) SetState(v VirtualNetworkState) {
	x.xxx_hidden_State = v
}

func (x *VirtualNetworkStatus) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *VirtualNetworkStatus) SetHub(v string) {
	x.xxx_hidden_Hub = v
}

func (x *VirtualNetworkStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VirtualNetworkStatus) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type VirtualNetworkStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the virtual network.
	State VirtualNetworkState
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, this might contain progress information like "Allocating IP address space" or
	// "Configuring network backend".
	//
	// For FAILED state, this contains error details explaining what went wrong, such as "Invalid CIDR range" or
	// "NetworkClass does not support dual-stack".
	//
	// For READY state, this is typically empty or contains confirmation like "Network ready for compute instances".
	Message *string
	// Identifier of the hub that was selected for this virtual network.
	// This is system-managed and used by the controller to track which hub cluster manages this network's resources.
	Hub string
}

func (b0 VirtualNetworkStatus_builder) Build() *VirtualNetworkStatus {
	m0 := &VirtualNetworkStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_Hub = b.Hub
	return m0
}

var File_osac_private_v1_virtual_network_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_virtual_network_type_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x0e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xdd, 0x02, 0x0a, 0x12, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1e, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe0, 0x41,
	0x02, 0xe0, 0x41, 0x05, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x0d,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x06, 0xe0, 0x41, 0x01, 0xe0, 0x41, 0x05, 0x52, 0x0c, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x09, 0x69, 0x70, 0x76,
	0x34, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41,
	0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x70, 0x76, 0x34, 0x43, 0x69, 0x64, 0x72, 0x88, 0x01, 0x01,
	0x12, 0x25, 0x0a, 0x09, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x05, 0x48, 0x01, 0x52, 0x08, 0x69, 0x70, 0x76, 0x36,
	0x43, 0x69, 0x64, 0x72, 0x88, 0x01, 0x01, 0x12, 0x4f, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x17, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe0, 0x41, 0x03, 0xe0, 0x41,
	0x05, 0x52, 0x16, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x70,
	0x76, 0x34, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x70, 0x76, 0x36,
	0x5f, 0x63, 0x69, 0x64, 0x72, 0x22, 0x8a, 0x01, 0x0a, 0x1a, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69,
	0x70, 0x76, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x70, 0x76, 0x34, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x69, 0x70, 0x76, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x70, 0x76, 0x36, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x64, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x22, 0x8f, 0x01, 0x0a, 0x14, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x68, 0x75, 0x62, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2a, 0xa2, 0x01, 0x0a, 0x13, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x21,
	0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x5f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x5f, 0x4e,
	0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41,
	0x4c, 0x5f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x56, 0x49, 0x52, 0x54, 0x55,
	0x41, 0x4c, 0x5f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xdc, 0x01, 0x0a, 0x13, 0x63, 0x6f,
	0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x42, 0x17, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58,
	0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_virtual_network_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_virtual_network_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_virtual_network_type_proto_goTypes = []any{
	(VirtualNetworkState)(0),           // 0: osac.private.v1.VirtualNetworkState
	(*VirtualNetwork)(nil),             // 1: osac.private.v1.VirtualNetwork
	(*VirtualNetworkSpec)(nil),         // 2: osac.private.v1.VirtualNetworkSpec
	(*VirtualNetworkCapabilities)(nil), // 3: osac.private.v1.VirtualNetworkCapabilities
	(*VirtualNetworkStatus)(nil),       // 4: osac.private.v1.VirtualNetworkStatus
	(*Metadata)(nil),                   // 5: osac.private.v1.Metadata
}
var file_osac_private_v1_virtual_network_type_proto_depIdxs = []int32{
	5, // 0: osac.private.v1.VirtualNetwork.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.VirtualNetwork.spec:type_name -> osac.private.v1.VirtualNetworkSpec
	4, // 2: osac.private.v1.VirtualNetwork.status:type_name -> osac.private.v1.VirtualNetworkStatus
	3, // 3: osac.private.v1.VirtualNetworkSpec.capabilities:type_name -> osac.private.v1.VirtualNetworkCapabilities
	0, // 4: osac.private.v1.VirtualNetworkStatus.state:type_name -> osac.private.v1.VirtualNetworkState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_virtual_network_type_proto_init() }
func file_osac_private_v1_virtual_network_type_proto_init() {
	if File_osac_private_v1_virtual_network_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_virtual_network_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_osac_private_v1_virtual_network_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_virtual_network_type_proto_rawDesc), len(file_osac_private_v1_virtual_network_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_virtual_network_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_virtual_network_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_virtual_network_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_virtual_network_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_virtual_network_type_proto = out.File
	file_osac_private_v1_virtual_network_type_proto_goTypes = nil
	file_osac_private_v1_virtual_network_type_proto_depIdxs = nil
}
