package provisioning

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/osac-project/osac-operator/api/v1alpha1"
	"github.com/osac-project/osac-operator/internal/webhook"
)

const (
	// EDAJobIDPrefix is the prefix for job IDs generated by the EDA provider.
	// EDA job IDs have the format "eda-webhook-N" where N is an incrementing counter.
	EDAJobIDPrefix = "eda-webhook-"

	// AAP finalizer names per resource type.
	// These finalizers are added by AAP playbooks during provisioning
	// and removed during deprovisioning to signal completion.
	ComputeInstanceAAPFinalizer = "osac.openshift.io/computeinstance-aap"
	ClusterOrderAAPFinalizer    = "osac.openshift.io/clusterorder-aap"
)

// IsEDAJobID returns true if the job ID is from the EDA provider.
// EDA job IDs have the format "eda-webhook-N", while AAP job IDs are numeric.
func IsEDAJobID(jobID string) bool {
	return strings.HasPrefix(jobID, EDAJobIDPrefix)
}

// WebhookClient is the interface for triggering webhooks to EDA.
// This matches the existing webhook_common.WebhookClient implementation.
type WebhookClient interface {
	TriggerWebhook(ctx context.Context, url string, resource webhook.Resource) (remainingTime time.Duration, err error)
}

// EDAProvider implements ProvisioningProvider using EDA webhooks.
// It maintains backward compatibility with the existing webhook-based approach.
// Each controller creates its own EDA provider with its specific webhook URLs.
type EDAProvider struct {
	webhookClient WebhookClient
	createURL     string
	deleteURL     string
}

// NewEDAProvider creates a new EDA provider with provision/deprovision webhook URLs.
func NewEDAProvider(
	webhookClient WebhookClient,
	createURL, deleteURL string,
) *EDAProvider {
	return &EDAProvider{
		webhookClient: webhookClient,
		createURL:     createURL,
		deleteURL:     deleteURL,
	}
}

// getAAPFinalizerName returns the AAP finalizer name for the resource type.
func getAAPFinalizerName(resource client.Object) (string, error) {
	switch resource.(type) {
	case *v1alpha1.ComputeInstance:
		return ComputeInstanceAAPFinalizer, nil
	case *v1alpha1.ClusterOrder:
		return ClusterOrderAAPFinalizer, nil
	default:
		return "", fmt.Errorf("unsupported resource type for AAP finalizer: %T", resource)
	}
}

// generateEDAJobID generates a unique job ID by scanning existing jobs and incrementing the counter.
// Returns IDs in the format "eda-webhook-N" where N is an incrementing counter.
func generateEDAJobID(jobs []v1alpha1.JobStatus) string {
	maxCounter := 0

	for _, job := range jobs {
		if IsEDAJobID(job.JobID) {
			// Extract counter from "eda-webhook-N"
			counterStr := strings.TrimPrefix(job.JobID, EDAJobIDPrefix)
			if counter, err := strconv.Atoi(counterStr); err == nil {
				if counter > maxCounter {
					maxCounter = counter
				}
			}
		}
	}

	return fmt.Sprintf("%s%d", EDAJobIDPrefix, maxCounter+1)
}

// TriggerProvision triggers provisioning via EDA webhook.
// Generates a unique job ID by scanning existing jobs.
// Returns RateLimitError if the request is rate-limited.
func (p *EDAProvider) TriggerProvision(ctx context.Context, resource client.Object) (*ProvisionResult, error) {
	createURL := p.createURL
	if createURL == "" {
		return nil, fmt.Errorf("create webhook URL not configured for resource type %T", resource)
	}

	webhookResource, ok := resource.(webhook.Resource)
	if !ok {
		return nil, fmt.Errorf("resource does not implement webhook.Resource interface")
	}

	remainingTime, err := p.webhookClient.TriggerWebhook(ctx, createURL, webhookResource)
	if err != nil {
		return nil, fmt.Errorf("failed to trigger create webhook: %w", err)
	}

	// If we're within the rate limit window, return rate limit error
	if remainingTime > 0 {
		return nil, &RateLimitError{RetryAfter: remainingTime}
	}

	// Generate unique job ID
	jobs := GetJobsFromResource(resource)
	jobID := generateEDAJobID(jobs)

	return &ProvisionResult{
		JobID:        jobID,
		InitialState: v1alpha1.JobStateRunning,
		Message:      "Webhook sent to EDA, provisioning in progress",
	}, nil
}

// GetProvisionStatus checks provisioning status.
// EDA doesn't provide status polling, so this always returns JobStateUnknown.
// The reconciler must check the CR annotation for completion.
func (p *EDAProvider) GetProvisionStatus(ctx context.Context, resource client.Object, jobID string) (ProvisionStatus, error) {
	return ProvisionStatus{
		JobID:   jobID,
		State:   v1alpha1.JobStateUnknown,
		Message: "EDA provider does not support status polling",
	}, nil
}

// TriggerDeprovision triggers deprovisioning via EDA webhook.
// Generates a unique job ID by scanning existing jobs.
// Returns RateLimitError if the request is rate-limited.
func (p *EDAProvider) TriggerDeprovision(ctx context.Context, resource client.Object) (*DeprovisionResult, error) {
	log := ctrllog.FromContext(ctx)

	// EDA only deprovisions if AAP finalizer exists (set by playbook during provision)
	aapFinalizer, err := getAAPFinalizerName(resource)
	if err != nil {
		return nil, err
	}
	if !controllerutil.ContainsFinalizer(resource, aapFinalizer) {
		log.Info("no AAP finalizer, skipping EDA deprovisioning", "finalizer", aapFinalizer)
		return &DeprovisionResult{
			Action:                 DeprovisionSkipped,
			BlockDeletionOnFailure: false,
		}, nil
	}

	// Trigger webhook
	deleteURL := p.deleteURL
	if deleteURL == "" {
		return nil, fmt.Errorf("delete webhook URL not configured for resource type %T", resource)
	}

	webhookResource, ok := resource.(webhook.Resource)
	if !ok {
		return nil, fmt.Errorf("resource does not implement webhook.Resource interface")
	}

	remainingTime, err := p.webhookClient.TriggerWebhook(ctx, deleteURL, webhookResource)
	if err != nil {
		return nil, fmt.Errorf("failed to trigger delete webhook: %w", err)
	}

	// If we're within the rate limit window, return rate limit error
	if remainingTime > 0 {
		return nil, &RateLimitError{RetryAfter: remainingTime}
	}

	// Generate unique job ID
	jobs := GetJobsFromResource(resource)
	jobID := generateEDAJobID(jobs)

	return &DeprovisionResult{
		Action:                 DeprovisionTriggered,
		JobID:                  jobID,
		BlockDeletionOnFailure: false,
	}, nil
}

// GetDeprovisionStatus checks deprovisioning status.
// EDA signals completion by having the AAP playbook remove the AAP finalizer.
// Returns Succeeded when finalizer is removed, Running while it still exists.
func (p *EDAProvider) GetDeprovisionStatus(ctx context.Context, resource client.Object, jobID string) (ProvisionStatus, error) {
	// Check if AAP finalizer has been removed (signals playbook completion)
	aapFinalizer, err := getAAPFinalizerName(resource)
	if err != nil {
		return ProvisionStatus{}, err
	}

	if !controllerutil.ContainsFinalizer(resource, aapFinalizer) {
		return ProvisionStatus{
			JobID:   jobID,
			State:   v1alpha1.JobStateSucceeded,
			Message: "AAP playbook completed (finalizer removed)",
		}, nil
	}

	// Finalizer still present - playbook still running
	return ProvisionStatus{
		JobID:   jobID,
		State:   v1alpha1.JobStateRunning,
		Message: "Waiting for AAP playbook to complete",
	}, nil
}

// Name returns the provider name for logging.
func (p *EDAProvider) Name() string {
	return "eda"
}
